namespace QuranLib;

internal static class BaseDataStore
{
    public static IEnumerable<Chapter> GetChapters()
    {
        return
        [
            new Chapter
            {
                Name = ChapterName.AlFatihah,
                ChapterNumber = 1,
                Juz = [1],
                ChapterNameArabic = "الفاتحة",
                ChapterNameEnglish = "The Opening",
                Ruku = 1,
                Order = 5,
                TotalVerse = 7,
            },
            new Chapter
            {
                Name = ChapterName.AlBaqarah,
                ChapterNumber = 2,
                Juz = [1, 2, 3],
                ChapterNameArabic = "البقرة",
                ChapterNameEnglish = "The Cow",
                Ruku = 40,
                Order = 87,
                TotalVerse = 286,
            },
            new Chapter
            {
                Name = ChapterName.AlImran,
                ChapterNumber = 3,
                Juz = [3, 4],
                ChapterNameArabic = "آل عمران",
                ChapterNameEnglish = "The Family of Imraan",
                Ruku = 20,
                Order = 89,
                TotalVerse = 200,
            },
            new Chapter
            {
                Name = ChapterName.AnNisa,
                ChapterNumber = 4,
                Juz = [4, 6],
                ChapterNameArabic = "النساء",
                ChapterNameEnglish = "The Women",
                Ruku = 24,
                Order = 92,
                TotalVerse = 176,
            },
            new Chapter
            {
                Name = ChapterName.AlMaidah,
                ChapterNumber = 5,
                Juz = [6, 7],
                ChapterNameArabic = "المائدة",
                ChapterNameEnglish = "The Table",
                Ruku = 16,
                Order = 112,
                TotalVerse = 120,
            },
            new Chapter
            {
                Name = ChapterName.AlAnam,
                ChapterNumber = 6,
                Juz = [7, 8],
                ChapterNameArabic = "الأنعام",
                ChapterNameEnglish = "The Cattle",
                Ruku = 20,
                Order = 55,
                TotalVerse = 165,
            },
            new Chapter
            {
                Name = ChapterName.AlAraf,
                ChapterNumber = 7,
                Juz = [8, 9],
                ChapterNameArabic = "الأعراف",
                ChapterNameEnglish = "The Heights",
                Ruku = 24,
                Order = 39,
                TotalVerse = 206,
            },
            new Chapter
            {
                Name = ChapterName.AlAnfal,
                ChapterNumber = 8,
                Juz = [9, 10],
                ChapterNameArabic = "الأنفال",
                ChapterNameEnglish = "The Spoils of War",
                Ruku = 10,
                Order = 88,
                TotalVerse = 75,
            },
            new Chapter
            {
                Name = ChapterName.AtTaubah,
                ChapterNumber = 9,
                Juz = [10, 11],
                ChapterNameArabic = "التوبة",
                ChapterNameEnglish = "The Repentance",
                Ruku = 16,
                Order = 113,
                TotalVerse = 129,
            },
            new Chapter
            {
                Name = ChapterName.Yunus,
                ChapterNumber = 10,
                Juz = [11],
                ChapterNameArabic = "يونس",
                ChapterNameEnglish = "Jonas",
                Ruku = 11,
                Order = 51,
                TotalVerse = 109,
            },
            new Chapter
            {
                Name = ChapterName.Hud,
                ChapterNumber = 11,
                Juz = [11, 12],
                ChapterNameArabic = "هود",
                ChapterNameEnglish = "Hud",
                Ruku = 10,
                Order = 52,
                TotalVerse = 123,
            },
            new Chapter
            {
                Name = ChapterName.Yusuf,
                ChapterNumber = 12,
                Juz = [12, 13],
                ChapterNameArabic = "يوسف",
                ChapterNameEnglish = "Joseph",
                Ruku = 12,
                Order = 53,
                TotalVerse = 111,
            },
            new Chapter
            {
                Name = ChapterName.ArRad,
                ChapterNumber = 13,
                Juz = [13],
                ChapterNameArabic = "الرعد",
                ChapterNameEnglish = "The Thunder",
                Ruku = 6,
                Order = 96,
                TotalVerse = 43,
            },
            new Chapter
            {
                Name = ChapterName.Ibrahim,
                ChapterNumber = 14,
                Juz = [13],
                ChapterNameArabic = "ابراهيم",
                ChapterNameEnglish = "Abraham",
                Ruku = 7,
                Order = 72,
                TotalVerse = 52,
            },
            new Chapter
            {
                Name = ChapterName.AlHijr,
                ChapterNumber = 15,
                Juz = [14],
                ChapterNameArabic = "الحجر",
                ChapterNameEnglish = "The Rock",
                Ruku = 6,
                Order = 54,
                TotalVerse = 99,
            },
            new Chapter
            {
                Name = ChapterName.AnNahl,
                ChapterNumber = 16,
                Juz = [14],
                ChapterNameArabic = "النحل",
                ChapterNameEnglish = "The Bee",
                Ruku = 16,
                Order = 70,
                TotalVerse = 128,
            },
            new Chapter
            {
                Name = ChapterName.AlIsra,
                ChapterNumber = 17,
                Juz = [15],
                ChapterNameArabic = "الإسراء",
                ChapterNameEnglish = "The Night Journey",
                Ruku = 12,
                Order = 50,
                TotalVerse = 111,
            },
            new Chapter
            {
                Name = ChapterName.AlKahf,
                ChapterNumber = 18,
                Juz = [15, 16],
                ChapterNameArabic = "الكهف",
                ChapterNameEnglish = "The Cave",
                Ruku = 12,
                Order = 69,
                TotalVerse = 110,
            },
            new Chapter
            {
                Name = ChapterName.Maryam,
                ChapterNumber = 19,
                Juz = [16],
                ChapterNameArabic = "مريم",
                ChapterNameEnglish = "Mary",
                Ruku = 6,
                Order = 44,
                TotalVerse = 98,
            },
            new Chapter
            {
                Name = ChapterName.TaHa,
                ChapterNumber = 20,
                Juz = [16],
                ChapterNameArabic = "طه",
                ChapterNameEnglish = "Taa-Haa",
                Ruku = 8,
                Order = 45,
                TotalVerse = 135,
            },
            new Chapter
            {
                Name = ChapterName.AlAnbiya,
                ChapterNumber = 21,
                Juz = [17],
                ChapterNameArabic = "الأنبياء",
                ChapterNameEnglish = "The Prophets",
                Ruku = 7,
                Order = 73,
                TotalVerse = 112,
            },
            new Chapter
            {
                Name = ChapterName.AlHajj,
                ChapterNumber = 22,
                Juz = [17],
                ChapterNameArabic = "الحج",
                ChapterNameEnglish = "The Pilgrimage",
                Ruku = 10,
                Order = 103,
                TotalVerse = 78,
            },
            new Chapter
            {
                Name = ChapterName.AlMuminun,
                ChapterNumber = 23,
                Juz = [18],
                ChapterNameArabic = "المؤمنون",
                ChapterNameEnglish = "The Believers",
                Ruku = 6,
                Order = 74,
                TotalVerse = 118,
            },
            new Chapter
            {
                Name = ChapterName.AnNur,
                ChapterNumber = 24,
                Juz = [18],
                ChapterNameArabic = "النور",
                ChapterNameEnglish = "The Light",
                Ruku = 9,
                Order = 102,
                TotalVerse = 64,
            },
            new Chapter
            {
                Name = ChapterName.AlFurqan,
                ChapterNumber = 25,
                Juz = [18, 19],
                ChapterNameArabic = "الفرقان",
                ChapterNameEnglish = "The Criterion",
                Ruku = 6,
                Order = 42,
                TotalVerse = 77,
            },
            new Chapter
            {
                Name = ChapterName.AshShuara,
                ChapterNumber = 26,
                Juz = [19],
                ChapterNameArabic = "الشعراء",
                ChapterNameEnglish = "The Poets",
                Ruku = 11,
                Order = 47,
                TotalVerse = 227,
            },
            new Chapter
            {
                Name = ChapterName.AnNaml,
                ChapterNumber = 27,
                Juz = [19, 20],
                ChapterNameArabic = "النمل",
                ChapterNameEnglish = "The Ant",
                Ruku = 7,
                Order = 48,
                TotalVerse = 93,
            },
            new Chapter
            {
                Name = ChapterName.AlQasas,
                ChapterNumber = 28,
                Juz = [20],
                ChapterNameArabic = "القصص",
                ChapterNameEnglish = "The Stories",
                Ruku = 8,
                Order = 49,
                TotalVerse = 88,
            },
            new Chapter
            {
                Name = ChapterName.AlAnkabut,
                ChapterNumber = 29,
                Juz = [20, 21],
                ChapterNameArabic = "العنكبوت",
                ChapterNameEnglish = "The Spider",
                Ruku = 7,
                Order = 85,
                TotalVerse = 69,
            },
            new Chapter
            {
                Name = ChapterName.ArRum,
                ChapterNumber = 30,
                Juz = [21],
                ChapterNameArabic = "الروم",
                ChapterNameEnglish = "The Romans",
                Ruku = 6,
                Order = 84,
                TotalVerse = 60,
            },
            new Chapter
            {
                Name = ChapterName.Luqman,
                ChapterNumber = 31,
                Juz = [21],
                ChapterNameArabic = "لقمان",
                ChapterNameEnglish = "Luqman",
                Ruku = 3,
                Order = 57,
                TotalVerse = 34,
            },
            new Chapter
            {
                Name = ChapterName.AsSajdah,
                ChapterNumber = 32,
                Juz = [21],
                ChapterNameArabic = "السجدة",
                ChapterNameEnglish = "The Prostration",
                Ruku = 3,
                Order = 75,
                TotalVerse = 30,
            },
            new Chapter
            {
                Name = ChapterName.AlAhzab,
                ChapterNumber = 33,
                Juz = [21, 22],
                ChapterNameArabic = "الأحزاب",
                ChapterNameEnglish = "The Clans",
                Ruku = 9,
                Order = 90,
                TotalVerse = 73,
            },
            new Chapter
            {
                Name = ChapterName.Saba,
                ChapterNumber = 34,
                Juz = [22],
                ChapterNameArabic = "سبإ",
                ChapterNameEnglish = "Sheba",
                Ruku = 6,
                Order = 58,
                TotalVerse = 54,
            },
            new Chapter
            {
                Name = ChapterName.Fatir,
                ChapterNumber = 35,
                Juz = [22],
                ChapterNameArabic = "فاطر",
                ChapterNameEnglish = "The Originator",
                Ruku = 5,
                Order = 43,
                TotalVerse = 45,
            },
            new Chapter
            {
                Name = ChapterName.YaSin,
                ChapterNumber = 36,
                Juz = [22, 23],
                ChapterNameArabic = "يس",
                ChapterNameEnglish = "Yaseen",
                Ruku = 5,
                Order = 41,
                TotalVerse = 83,
            },
            new Chapter
            {
                Name = ChapterName.AsSaffat,
                ChapterNumber = 37,
                Juz = [23],
                ChapterNameArabic = "الصافات",
                ChapterNameEnglish = "Those drawn up in Ranks",
                Ruku = 5,
                Order = 56,
                TotalVerse = 182,
            },
            new Chapter
            {
                Name = ChapterName.Sad,
                ChapterNumber = 38,
                Juz = [23],
                ChapterNameArabic = "ص",
                ChapterNameEnglish = "The letter Saad",
                Ruku = 5,
                Order = 38,
                TotalVerse = 88,
            },
            new Chapter
            {
                Name = ChapterName.AzZumar,
                ChapterNumber = 39,
                Juz = [23, 24],
                ChapterNameArabic = "الزمر",
                ChapterNameEnglish = "The Groups",
                Ruku = 8,
                Order = 59,
                TotalVerse = 75,
            },
            new Chapter
            {
                Name = ChapterName.Ghafir,
                ChapterNumber = 40,
                Juz = [24],
                ChapterNameArabic = "غافر",
                ChapterNameEnglish = "The Forgiver",
                Ruku = 9,
                Order = 60,
                TotalVerse = 85,
            },
            new Chapter
            {
                Name = ChapterName.Fussilat,
                ChapterNumber = 41,
                Juz = [24, 25],
                ChapterNameArabic = "فصلت",
                ChapterNameEnglish = "Explained in detail",
                Ruku = 6,
                Order = 61,
                TotalVerse = 54,
            },
            new Chapter
            {
                Name = ChapterName.AshShura,
                ChapterNumber = 42,
                Juz = [25],
                ChapterNameArabic = "الشورى",
                ChapterNameEnglish = "Consultation",
                Ruku = 5,
                Order = 62,
                TotalVerse = 53,
            },
            new Chapter
            {
                Name = ChapterName.AzZukhruf,
                ChapterNumber = 43,
                Juz = [25],
                ChapterNameArabic = "الزخرف",
                ChapterNameEnglish = "Ornaments of gold",
                Ruku = 7,
                Order = 63,
                TotalVerse = 89,
            },
            new Chapter
            {
                Name = ChapterName.AdDukhan,
                ChapterNumber = 44,
                Juz = [25],
                ChapterNameArabic = "الدخان",
                ChapterNameEnglish = "The Smoke",
                Ruku = 3,
                Order = 64,
                TotalVerse = 59,
            },
            new Chapter
            {
                Name = ChapterName.AlJathiyah,
                ChapterNumber = 45,
                Juz = [25],
                ChapterNameArabic = "الجاثية",
                ChapterNameEnglish = "Crouching",
                Ruku = 4,
                Order = 65,
                TotalVerse = 37,
            },
            new Chapter
            {
                Name = ChapterName.AlAhqaf,
                ChapterNumber = 46,
                Juz = [26],
                ChapterNameArabic = "الأحقاف",
                ChapterNameEnglish = "The Dunes",
                Ruku = 4,
                Order = 66,
                TotalVerse = 35,
            },
            new Chapter
            {
                Name = ChapterName.Muhammad,
                ChapterNumber = 47,
                Juz = [26],
                ChapterNameArabic = "محمد",
                ChapterNameEnglish = "Muhammad",
                Ruku = 4,
                Order = 95,
                TotalVerse = 38,
            },
            new Chapter
            {
                Name = ChapterName.AlFath,
                ChapterNumber = 48,
                Juz = [26],
                ChapterNameArabic = "الفتح",
                ChapterNameEnglish = "The Victory",
                Ruku = 4,
                Order = 111,
                TotalVerse = 29,
            },
            new Chapter
            {
                Name = ChapterName.AlHujurat,
                ChapterNumber = 49,
                Juz = [26],
                ChapterNameArabic = "الحجرات",
                ChapterNameEnglish = "The Inner Apartments",
                Ruku = 2,
                Order = 106,
                TotalVerse = 18,
            },
            new Chapter
            {
                Name = ChapterName.Qaf,
                ChapterNumber = 50,
                Juz = [26],
                ChapterNameArabic = "ق",
                ChapterNameEnglish = "The letter Qaaf",
                Ruku = 3,
                Order = 34,
                TotalVerse = 45,
            },
            new Chapter
            {
                Name = ChapterName.AdDhariyat,
                ChapterNumber = 51,
                Juz = [26, 27],
                ChapterNameArabic = "الذاريات",
                ChapterNameEnglish = "The Winnowing Winds",
                Ruku = 3,
                Order = 67,
                TotalVerse = 60,
            },
            new Chapter
            {
                Name = ChapterName.AtTur,
                ChapterNumber = 52,
                Juz = [27],
                ChapterNameArabic = "الطور",
                ChapterNameEnglish = "The Mount",
                Ruku = 2,
                Order = 76,
                TotalVerse = 49,
            },
            new Chapter
            {
                Name = ChapterName.AnNajm,
                ChapterNumber = 53,
                Juz = [27],
                ChapterNameArabic = "النجم",
                ChapterNameEnglish = "The Star",
                Ruku = 3,
                Order = 23,
                TotalVerse = 62,
            },
            new Chapter
            {
                Name = ChapterName.AlQamar,
                ChapterNumber = 54,
                Juz = [27],
                ChapterNameArabic = "القمر",
                ChapterNameEnglish = "The Moon",
                Ruku = 3,
                Order = 37,
                TotalVerse = 55,
            },
            new Chapter
            {
                Name = ChapterName.ArRahman,
                ChapterNumber = 55,
                Juz = [27],
                ChapterNameArabic = "الرحمن",
                ChapterNameEnglish = "The Beneficent",
                Ruku = 3,
                Order = 97,
                TotalVerse = 78,
            },
            new Chapter
            {
                Name = ChapterName.AlWaqiah,
                ChapterNumber = 56,
                Juz = [27],
                ChapterNameArabic = "الواقعة",
                ChapterNameEnglish = "The Inevitable",
                Ruku = 3,
                Order = 46,
                TotalVerse = 96,
            },
            new Chapter
            {
                Name = ChapterName.AlHadeed,
                ChapterNumber = 57,
                Juz = [27],
                ChapterNameArabic = "الحديد",
                ChapterNameEnglish = "The Iron",
                Ruku = 4,
                Order = 94,
                TotalVerse = 29,
            },
            new Chapter
            {
                Name = ChapterName.AlMujadilah,
                ChapterNumber = 58,
                Juz = [28],
                ChapterNameArabic = "المجادلة",
                ChapterNameEnglish = "The Pleading Woman",
                Ruku = 3,
                Order = 105,
                TotalVerse = 22,
            },
            new Chapter
            {
                Name = ChapterName.AlHashr,
                ChapterNumber = 59,
                Juz = [28],
                ChapterNameArabic = "الحشر",
                ChapterNameEnglish = "The Exile",
                Ruku = 3,
                Order = 101,
                TotalVerse = 24,
            },
            new Chapter
            {
                Name = ChapterName.AlMumtahanah,
                ChapterNumber = 60,
                Juz = [28],
                ChapterNameArabic = "الممتحنة",
                ChapterNameEnglish = "She that is to be examined",
                Ruku = 2,
                Order = 91,
                TotalVerse = 13,
            },
            new Chapter
            {
                Name = ChapterName.AsSaff,
                ChapterNumber = 61,
                Juz = [28],
                ChapterNameArabic = "الصف",
                ChapterNameEnglish = "The Ranks",
                Ruku = 2,
                Order = 109,
                TotalVerse = 14,
            },
            new Chapter
            {
                Name = ChapterName.AlJumuah,
                ChapterNumber = 62,
                Juz = [28],
                ChapterNameArabic = "الجمعة",
                ChapterNameEnglish = "Friday",
                Ruku = 2,
                Order = 110,
                TotalVerse = 11,
            },
            new Chapter
            {
                Name = ChapterName.AlMunafiqun,
                ChapterNumber = 63,
                Juz = [28],
                ChapterNameArabic = "المنافقون",
                ChapterNameEnglish = "The Hypocrites",
                Ruku = 2,
                Order = 104,
                TotalVerse = 11,
            },
            new Chapter
            {
                Name = ChapterName.AtTaghabun,
                ChapterNumber = 64,
                Juz = [28],
                ChapterNameArabic = "التغابن",
                ChapterNameEnglish = "Mutual Disillusion",
                Ruku = 2,
                Order = 108,
                TotalVerse = 18,
            },
            new Chapter
            {
                Name = ChapterName.AtTalaq,
                ChapterNumber = 65,
                Juz = [28],
                ChapterNameArabic = "الطلاق",
                ChapterNameEnglish = "Divorce",
                Ruku = 2,
                Order = 99,
                TotalVerse = 12,
            },
            new Chapter
            {
                Name = ChapterName.AtTahreem,
                ChapterNumber = 66,
                Juz = [28],
                ChapterNameArabic = "التحريم",
                ChapterNameEnglish = "The Prohibition",
                Ruku = 2,
                Order = 107,
                TotalVerse = 12,
            },
            new Chapter
            {
                Name = ChapterName.AlMulk,
                ChapterNumber = 67,
                Juz = [29],
                ChapterNameArabic = "الملك",
                ChapterNameEnglish = "The Sovereignty",
                Ruku = 2,
                Order = 77,
                TotalVerse = 30,
            },
            new Chapter
            {
                Name = ChapterName.AlQalam,
                ChapterNumber = 68,
                Juz = [29],
                ChapterNameArabic = "القلم",
                ChapterNameEnglish = "The Pen",
                Ruku = 2,
                Order = 2,
                TotalVerse = 52,
            },
            new Chapter
            {
                Name = ChapterName.AlHaqqah,
                ChapterNumber = 69,
                Juz = [29],
                ChapterNameArabic = "الحاقة",
                ChapterNameEnglish = "The Reality",
                Ruku = 2,
                Order = 78,
                TotalVerse = 52,
            },
            new Chapter
            {
                Name = ChapterName.AlMaaarij,
                ChapterNumber = 70,
                Juz = [29],
                ChapterNameArabic = "المعارج",
                ChapterNameEnglish = "The Ascending Stairways",
                Ruku = 2,
                Order = 79,
                TotalVerse = 44,
            },
            new Chapter
            {
                Name = ChapterName.Nuh,
                ChapterNumber = 71,
                Juz = [29],
                ChapterNameArabic = "نوح",
                ChapterNameEnglish = "Noah",
                Ruku = 2,
                Order = 71,
                TotalVerse = 28,
            },
            new Chapter
            {
                Name = ChapterName.AlJinn,
                ChapterNumber = 72,
                Juz = [29],
                ChapterNameArabic = "الجن",
                ChapterNameEnglish = "The Jinn",
                Ruku = 2,
                Order = 40,
                TotalVerse = 28,
            },
            new Chapter
            {
                Name = ChapterName.AlMuzzammil,
                ChapterNumber = 73,
                Juz = [29],
                ChapterNameArabic = "المزمل",
                ChapterNameEnglish = "The Enshrouded One",
                Ruku = 2,
                Order = 3,
                TotalVerse = 20,
            },
            new Chapter
            {
                Name = ChapterName.AlMuddathir,
                ChapterNumber = 74,
                Juz = [29],
                ChapterNameArabic = "المدثر",
                ChapterNameEnglish = "The Cloaked One",
                Ruku = 2,
                Order = 4,
                TotalVerse = 56,
            },
            new Chapter
            {
                Name = ChapterName.AlQiyamah,
                ChapterNumber = 75,
                Juz = [29],
                ChapterNameArabic = "القيامة",
                ChapterNameEnglish = "The Resurrection",
                Ruku = 2,
                Order = 31,
                TotalVerse = 40,
            },
            new Chapter
            {
                Name = ChapterName.AlInsan,
                ChapterNumber = 76,
                Juz = [29],
                ChapterNameArabic = "الانسان",
                ChapterNameEnglish = "Man",
                Ruku = 2,
                Order = 98,
                TotalVerse = 31,
            },
            new Chapter
            {
                Name = ChapterName.AlMursalat,
                ChapterNumber = 77,
                Juz = [29],
                ChapterNameArabic = "المرسلات",
                ChapterNameEnglish = "The Emissaries",
                Ruku = 2,
                Order = 33,
                TotalVerse = 50,
            },
            new Chapter
            {
                Name = ChapterName.AnNaba,
                ChapterNumber = 78,
                Juz = [30],
                ChapterNameArabic = "النبإ",
                ChapterNameEnglish = "The Announcement",
                Ruku = 2,
                Order = 80,
                TotalVerse = 40,
            },
            new Chapter
            {
                Name = ChapterName.AnNaziat,
                ChapterNumber = 79,
                Juz = [30],
                ChapterNameArabic = "النازعات",
                ChapterNameEnglish = "Those who drag forth",
                Ruku = 2,
                Order = 81,
                TotalVerse = 46,
            },
            new Chapter
            {
                Name = ChapterName.Abasa,
                ChapterNumber = 80,
                Juz = [30],
                ChapterNameArabic = "عبس",
                ChapterNameEnglish = "He frowned",
                Ruku = 1,
                Order = 24,
                TotalVerse = 42,
            },
            new Chapter
            {
                Name = ChapterName.AtTakwir,
                ChapterNumber = 81,
                Juz = [30],
                ChapterNameArabic = "التكوير",
                ChapterNameEnglish = "The Overthrowing",
                Ruku = 1,
                Order = 7,
                TotalVerse = 29,
            },
            new Chapter
            {
                Name = ChapterName.AlInfitar,
                ChapterNumber = 82,
                Juz = [30],
                ChapterNameArabic = "الإنفطار",
                ChapterNameEnglish = "The Cleaving",
                Ruku = 1,
                Order = 82,
                TotalVerse = 19,
            },
            new Chapter
            {
                Name = ChapterName.AlMutaffifeen,
                ChapterNumber = 83,
                Juz = [30],
                ChapterNameArabic = "المطففين",
                ChapterNameEnglish = "Defrauding",
                Ruku = 1,
                Order = 86,
                TotalVerse = 36,
            },
            new Chapter
            {
                Name = ChapterName.AlInshiqaq,
                ChapterNumber = 84,
                Juz = [30],
                ChapterNameArabic = "الإنشقاق",
                ChapterNameEnglish = "The Splitting Open",
                Ruku = 1,
                Order = 83,
                TotalVerse = 25,
            },
            new Chapter
            {
                Name = ChapterName.AlBuruj,
                ChapterNumber = 85,
                Juz = [30],
                ChapterNameArabic = "البروج",
                ChapterNameEnglish = "The Constellations",
                Ruku = 1,
                Order = 27,
                TotalVerse = 22,
            },
            new Chapter
            {
                Name = ChapterName.AtTariq,
                ChapterNumber = 86,
                Juz = [30],
                ChapterNameArabic = "الطارق",
                ChapterNameEnglish = "The Morning Star",
                Ruku = 1,
                Order = 36,
                TotalVerse = 17,
            },
            new Chapter
            {
                Name = ChapterName.AlAla,
                ChapterNumber = 87,
                Juz = [30],
                ChapterNameArabic = "الأعلى",
                ChapterNameEnglish = "The Most High",
                Ruku = 1,
                Order = 8,
                TotalVerse = 19,
            },
            new Chapter
            {
                Name = ChapterName.AlGhashiyah,
                ChapterNumber = 88,
                Juz = [30],
                ChapterNameArabic = "الغاشية",
                ChapterNameEnglish = "The Overwhelming",
                Ruku = 1,
                Order = 68,
                TotalVerse = 26,
            },
            new Chapter
            {
                Name = ChapterName.AlFajr,
                ChapterNumber = 89,
                Juz = [30],
                ChapterNameArabic = "الفجر",
                ChapterNameEnglish = "The Dawn",
                Ruku = 1,
                Order = 10,
                TotalVerse = 30,
            },
            new Chapter
            {
                Name = ChapterName.AlBalad,
                ChapterNumber = 90,
                Juz = [30],
                ChapterNameArabic = "البلد",
                ChapterNameEnglish = "The City",
                Ruku = 1,
                Order = 35,
                TotalVerse = 20,
            },
            new Chapter
            {
                Name = ChapterName.AshShams,
                ChapterNumber = 91,
                Juz = [30],
                ChapterNameArabic = "الشمس",
                ChapterNameEnglish = "The Sun",
                Ruku = 1,
                Order = 26,
                TotalVerse = 15,
            },
            new Chapter
            {
                Name = ChapterName.AlLail,
                ChapterNumber = 92,
                Juz = [30],
                ChapterNameArabic = "الليل",
                ChapterNameEnglish = "The Night",
                Ruku = 1,
                Order = 9,
                TotalVerse = 21,
            },
            new Chapter
            {
                Name = ChapterName.AdDhuha,
                ChapterNumber = 93,
                Juz = [30],
                ChapterNameArabic = "الضحى",
                ChapterNameEnglish = "The Morning Hours",
                Ruku = 1,
                Order = 11,
                TotalVerse = 11,
            },
            new Chapter
            {
                Name = ChapterName.AshSharh,
                ChapterNumber = 94,
                Juz = [30],
                ChapterNameArabic = "الشرح",
                ChapterNameEnglish = "The Consolation",
                Ruku = 1,
                Order = 12,
                TotalVerse = 8,
            },
            new Chapter
            {
                Name = ChapterName.AtTin,
                ChapterNumber = 95,
                Juz = [30],
                ChapterNameArabic = "التين",
                ChapterNameEnglish = "The Fig",
                Ruku = 1,
                Order = 28,
                TotalVerse = 8,
            },
            new Chapter
            {
                Name = ChapterName.AlAlaq,
                ChapterNumber = 96,
                Juz = [30],
                ChapterNameArabic = "العلق",
                ChapterNameEnglish = "The Clot",
                Ruku = 1,
                Order = 1,
                TotalVerse = 19,
            },
            new Chapter
            {
                Name = ChapterName.AlQadr,
                ChapterNumber = 97,
                Juz = [30],
                ChapterNameArabic = "القدر",
                ChapterNameEnglish = "The Power, Fate",
                Ruku = 1,
                Order = 25,
                TotalVerse = 5,
            },
            new Chapter
            {
                Name = ChapterName.AlBayyinah,
                ChapterNumber = 98,
                Juz = [30],
                ChapterNameArabic = "البينة",
                ChapterNameEnglish = "The Evidence",
                Ruku = 1,
                Order = 100,
                TotalVerse = 8,
            },
            new Chapter
            {
                Name = ChapterName.AzZalzala,
                ChapterNumber = 99,
                Juz = [30],
                ChapterNameArabic = "الزلزلة",
                ChapterNameEnglish = "The Earthquake",
                Ruku = 1,
                Order = 93,
                TotalVerse = 8,
            },
            new Chapter
            {
                Name = ChapterName.AlAdiyat,
                ChapterNumber = 100,
                Juz = [30],
                ChapterNameArabic = "العاديات",
                ChapterNameEnglish = "The Chargers",
                Ruku = 1,
                Order = 14,
                TotalVerse = 11,
            },
            new Chapter
            {
                Name = ChapterName.AlQariah,
                ChapterNumber = 101,
                Juz = [30],
                ChapterNameArabic = "القارعة",
                ChapterNameEnglish = "The Calamity",
                Ruku = 1,
                Order = 30,
                TotalVerse = 11,
            },
            new Chapter
            {
                Name = ChapterName.AtTakathur,
                ChapterNumber = 102,
                Juz = [30],
                ChapterNameArabic = "التكاثر",
                ChapterNameEnglish = "Competition",
                Ruku = 1,
                Order = 16,
                TotalVerse = 8,
            },
            new Chapter
            {
                Name = ChapterName.AlAsr,
                ChapterNumber = 103,
                Juz = [30],
                ChapterNameArabic = "العصر",
                ChapterNameEnglish = "The Declining Day, Epoch",
                Ruku = 1,
                Order = 13,
                TotalVerse = 3,
            },
            new Chapter
            {
                Name = ChapterName.AlHumazah,
                ChapterNumber = 104,
                Juz = [30],
                ChapterNameArabic = "الهمزة",
                ChapterNameEnglish = "The Traducer",
                Ruku = 1,
                Order = 32,
                TotalVerse = 9,
            },
            new Chapter
            {
                Name = ChapterName.AlFil,
                ChapterNumber = 105,
                Juz = [30],
                ChapterNameArabic = "الفيل",
                ChapterNameEnglish = "The Elephant",
                Ruku = 1,
                Order = 19,
                TotalVerse = 5,
            },
            new Chapter
            {
                Name = ChapterName.Qurayish,
                ChapterNumber = 106,
                Juz = [30],
                ChapterNameArabic = "قريش",
                ChapterNameEnglish = "Quraysh",
                Ruku = 1,
                Order = 29,
                TotalVerse = 4,
            },
            new Chapter
            {
                Name = ChapterName.AlMaun,
                ChapterNumber = 107,
                Juz = [30],
                ChapterNameArabic = "الماعون",
                ChapterNameEnglish = "Almsgiving",
                Ruku = 1,
                Order = 17,
                TotalVerse = 7,
            },
            new Chapter
            {
                Name = ChapterName.AlKawthar,
                ChapterNumber = 108,
                Juz = [30],
                ChapterNameArabic = "الكوثر",
                ChapterNameEnglish = "Abundance",
                Ruku = 1,
                Order = 15,
                TotalVerse = 3,
            },
            new Chapter
            {
                Name = ChapterName.AlKafirun,
                ChapterNumber = 109,
                Juz = [30],
                ChapterNameArabic = "الكافرون",
                ChapterNameEnglish = "The Disbelievers",
                Ruku = 1,
                Order = 18,
                TotalVerse = 6,
            },
            new Chapter
            {
                Name = ChapterName.AnNasr,
                ChapterNumber = 110,
                Juz = [30],
                ChapterNameArabic = "النصر",
                ChapterNameEnglish = "Divine Support",
                Ruku = 1,
                Order = 114,
                TotalVerse = 3,
            },
            new Chapter
            {
                Name = ChapterName.AlMasad,
                ChapterNumber = 111,
                Juz = [30],
                ChapterNameArabic = "المسد",
                ChapterNameEnglish = "The Palm Fibre",
                Ruku = 1,
                Order = 6,
                TotalVerse = 5,
            },
            new Chapter
            {
                Name = ChapterName.AlIkhlas,
                ChapterNumber = 112,
                Juz = [30],
                ChapterNameArabic = "الإخلاص",
                ChapterNameEnglish = "Sincerity",
                Ruku = 1,
                Order = 22,
                TotalVerse = 4,
            },
            new Chapter
            {
                Name = ChapterName.AlFalaq,
                ChapterNumber = 113,
                Juz = [30],
                ChapterNameArabic = "الفلق",
                ChapterNameEnglish = "The Dawn",
                Ruku = 1,
                Order = 20,
                TotalVerse = 5,
            },
            new Chapter
            {
                Name = ChapterName.AnNas,
                ChapterNumber = 114,
                Juz = [30],
                ChapterNameArabic = "الناس",
                ChapterNameEnglish = "Mankind",
                Ruku = 1,
                Order = 21,
                TotalVerse = 6,
            }
        ];
    }
}
