//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranLib {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CleanAyahResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CleanAyahResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranLib.CleanAyahResource", typeof(CleanAyahResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم
        ///الحمد لله رب العالمین
        ///الرحمن الرحیم
        ///مالک یوم الدین
        ///ایاک نعبد وایاک نستعین
        ///اهدنا الصراط المستقیم
        ///صراط الذین انعمت علیهم غیر المغضوب علیهم ولا الضالین.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الر تلک ایات الکتاب الحکیم
        ///اکان للناس عجبا ان اوحینا الى رجل منهم ان انذر الناس وبشر الذین امنوا ان لهم قدم صدق عند ربهم قال الکافرون ان هذا لساحر مبین
        ///ان ربکم الله الذی خلق السماوات والارض فی ست ایام ثم استوى على العرش یدبر الامر ما من شفیع الا من بعد اذنه ذلکم الله ربکم فاعبدوه افلا تذکرون
        ///الیه مرجعکم جمیعا وعد الله حقا انه یبدا الخلق ثم یعیده لیجزی الذین امنوا وعملوا الصالحات بالقسط والذین کفروا لهم شراب من حمیم وعذاب الیم بما کانوا یکفرون
        ///هو الذی جعل الشمس ضیا والقمر نورا وقدره من [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والعادیات ضبحا
        ///فالموریات قدحا
        ///فالمغیرات صبحا
        ///فاثرن به نقعا
        ///فوسطن به جمعا
        ///ان الانسان لربه لکنود
        ///وانه على ذلک لشهید
        ///وانه لحب الخیر لشدید
        ///افلا یعلم اذا بعثر ما فی القبور
        ///وحصل ما فی الصدور
        ///ان ربهم بهم یومئذ لخبیر.
        /// </summary>
        internal static string _100 {
            get {
                return ResourceManager.GetString("_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم القارع
        ///ما القارع
        ///وما ادراک ما القارع
        ///یوم یکون الناس کالفراش المبثوث
        ///وتکون الجبال کالعهن المنفوش
        ///فاما من ثقلت موازینه
        ///فهو فی عیش راضی
        ///واما من خفت موازینه
        ///فامه هاوی
        ///وما ادراک ما هیه
        ///نار حامی.
        /// </summary>
        internal static string _101 {
            get {
                return ResourceManager.GetString("_101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الهاکم التکاثر
        ///حتى زرتم المقابر
        ///کلا سوف تعلمون
        ///ثم کلا سوف تعلمون
        ///کلا لو تعلمون علم الیقین
        ///لترون الجحیم
        ///ثم لترونها عین الیقین
        ///ثم لتسالن یومئذ عن النعیم.
        /// </summary>
        internal static string _102 {
            get {
                return ResourceManager.GetString("_102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والعصر
        ///ان الانسان لفی خسر
        ///الا الذین امنوا وعملوا الصالحات وتواصوا بالحق وتواصوا بالصبر.
        /// </summary>
        internal static string _103 {
            get {
                return ResourceManager.GetString("_103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ویل لکل همز لمز
        ///الذی جمع مالا وعدده
        ///یحسب ان ماله اخلده
        ///کلا لینبذن فی الحطم
        ///وما ادراک ما الحطم
        ///نار الله الموقد
        ///التی تطلع على الافئد
        ///انها علیهم موصد
        ///فی عمد ممدد.
        /// </summary>
        internal static string _104 {
            get {
                return ResourceManager.GetString("_104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم تر کیف فعل ربک باصحاب الفیل
        ///الم یجعل کیدهم فی تضلیل
        ///وارسل علیهم طیرا ابابیل
        ///ترمیهم بحجار من سجیل
        ///فجعلهم کعصف ماکول.
        /// </summary>
        internal static string _105 {
            get {
                return ResourceManager.GetString("_105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم لایلاف قریش
        ///ایلافهم رحل الشتا والصیف
        ///فلیعبدوا رب هذا البیت
        ///الذی اطعمهم من جوع وامنهم من خوف.
        /// </summary>
        internal static string _106 {
            get {
                return ResourceManager.GetString("_106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ارایت الذی یکذب بالدین
        ///فذلک الذی یدع الیتیم
        ///ولا یحض على طعام المسکین
        ///فویل للمصلین
        ///الذین هم عن صلاتهم ساهون
        ///الذین هم یراون
        ///ویمنعون الماعون.
        /// </summary>
        internal static string _107 {
            get {
                return ResourceManager.GetString("_107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم انا اعطیناک الکوثر
        ///فصل لربک وانحر
        ///ان شانئک هو الابتر.
        /// </summary>
        internal static string _108 {
            get {
                return ResourceManager.GetString("_108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قل یا ایها الکافرون
        ///لا اعبد ما تعبدون
        ///ولا انتم عابدون ما اعبد
        ///ولا انا عابد ما عبدتم
        ///ولا انتم عابدون ما اعبد
        ///لکم دینکم ولی دین.
        /// </summary>
        internal static string _109 {
            get {
                return ResourceManager.GetString("_109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الر کتاب احکمت ایاته ثم فصلت من لدن حکیم خبیر
        ///الا تعبدوا الا الله اننی لکم منه نذیر وبشیر
        ///وان استغفروا ربکم ثم توبوا الیه یمتعکم متاعا حسنا الى اجل مسمى ویوت کل ذی فضل فضله وان تولوا فانی اخاف علیکم عذاب یوم کبیر
        ///الى الله مرجعکم وهو على کل شی قدیر
        ///الا انهم یثنون صدورهم لیستخفوا منه الا حین یستغشون ثیابهم یعلم ما یسرون وما یعلنون انه علیم بذات الصدور
        ///وما من داب فی الارض الا على الله رزقها ویعلم مستقرها ومستودعها کل فی کتاب مبین
        ///وهو الذی خلق السماوات والارض فی ست ایام وکان عرشه على الما [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _11 {
            get {
                return ResourceManager.GetString("_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا جا نصر الله والفتح
        ///ورایت الناس یدخلون فی دین الله افواجا
        ///فسبح بحمد ربک واستغفره انه کان توابا.
        /// </summary>
        internal static string _110 {
            get {
                return ResourceManager.GetString("_110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم تبت یدا ابی لهب وتب
        ///ما اغنى عنه ماله وما کسب
        ///سیصلى نارا ذات لهب
        ///وامراته حمال الحطب
        ///فی جیدها حبل من مسد.
        /// </summary>
        internal static string _111 {
            get {
                return ResourceManager.GetString("_111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قل هو الله احد
        ///الله الصمد
        ///لم یلد ولم یولد
        ///ولم یکن له کفوا احد.
        /// </summary>
        internal static string _112 {
            get {
                return ResourceManager.GetString("_112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قل اعوذ برب الفلق
        ///من شر ما خلق
        ///ومن شر غاسق اذا وقب
        ///ومن شر النفاثات فی العقد
        ///ومن شر حاسد اذا حسد.
        /// </summary>
        internal static string _113 {
            get {
                return ResourceManager.GetString("_113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قل اعوذ برب الناس
        ///ملک الناس
        ///اله الناس
        ///من شر الوسواس الخناس
        ///الذی یوسوس فی صدور الناس
        ///من الجن والناس.
        /// </summary>
        internal static string _114 {
            get {
                return ResourceManager.GetString("_114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الر تلک ایات الکتاب المبین
        ///انا انزلناه قرانا عربیا لعلکم تعقلون
        ///نحن نقص علیک احسن القصص بما اوحینا الیک هذا القران وان کنت من قبله لمن الغافلین
        ///اذ قال یوسف لابیه یا ابت انی رایت احد عشر کوکبا والشمس والقمر رایتهم لی ساجدین
        ///قال یا بنی لا تقصص رویاک على اخوتک فیکیدوا لک کیدا ان الشیطان للانسان عدو مبین
        ///وکذلک یجتبیک ربک ویعلمک من تاویل الاحادیث ویتم نعمته علیک وعلى ال یعقوب کما اتمها على ابویک من قبل ابراهیم واسحاق ان ربک علیم حکیم
        ///لقد کان فی یوسف واخوته ایات للسائلین
        ///اذ قالوا لیوسف واخو [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _12 {
            get {
                return ResourceManager.GetString("_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم المر تلک ایات الکتاب والذی انزل الیک من ربک الحق ولکن اکثر الناس لا یومنون
        ///الله الذی رفع السماوات بغیر عمد ترونها ثم استوى على العرش وسخر الشمس والقمر کل یجری لاجل مسمى یدبر الامر یفصل الایات لعلکم بلقا ربکم توقنون
        ///وهو الذی مد الارض وجعل فیها رواسی وانهارا ومن کل الثمرات جعل فیها زوجین اثنین یغشی اللیل النهار ان فی ذلک لایات لقوم یتفکرون
        ///وفی الارض قطع متجاورات وجنات من اعناب وزرع ونخیل صنوان وغیر صنوان یسقى بما واحد ونفضل بعضها على بعض فی الاکل ان فی ذلک لایات لقوم یعقلون
        ///وان تعجب فعج [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _13 {
            get {
                return ResourceManager.GetString("_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الر کتاب انزلناه الیک لتخرج الناس من الظلمات الى النور باذن ربهم الى صراط العزیز الحمید
        ///الله الذی له ما فی السماوات وما فی الارض وویل للکافرین من عذاب شدید
        ///الذین یستحبون الحیا الدنیا على الاخر ویصدون عن سبیل الله ویبغونها عوجا اولئک فی ضلال بعید
        ///وما ارسلنا من رسول الا بلسان قومه لیبین لهم فیضل الله من یشا ویهدی من یشا وهو العزیز الحکیم
        ///ولقد ارسلنا موسى بایاتنا ان اخرج قومک من الظلمات الى النور وذکرهم بایام الله ان فی ذلک لایات لکل صبار شکور
        ///واذ قال موسى لقومه اذکروا نعم الله علیکم اذ  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _14 {
            get {
                return ResourceManager.GetString("_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الر تلک ایات الکتاب وقران مبین
        ///ربما یود الذین کفروا لو کانوا مسلمین
        ///ذرهم یاکلوا ویتمتعوا ویلههم الامل فسوف یعلمون
        ///وما اهلکنا من قری الا ولها کتاب معلوم
        ///ما تسبق من ام اجلها وما یستاخرون
        ///وقالوا یا ایها الذی نزل علیه الذکر انک لمجنون
        ///لو ما تاتینا بالملائک ان کنت من الصادقین
        ///ما ننزل الملائک الا بالحق وما کانوا اذا منظرین
        ///انا نحن نزلنا الذکر وانا له لحافظون
        ///ولقد ارسلنا من قبلک فی شیع الاولین
        ///وما یاتیهم من رسول الا کانوا به یستهزئون
        ///کذلک نسلکه فی قلوب المجرمین
        ///لا یومنون به وقد خلت سن الاولی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _15 {
            get {
                return ResourceManager.GetString("_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اتى امر الله فلا تستعجلوه سبحانه وتعالى عما یشرکون
        ///ینزل الملائک بالروح من امره على من یشا من عباده ان انذروا انه لا اله الا انا فاتقون
        ///خلق السماوات والارض بالحق تعالى عما یشرکون
        ///خلق الانسان من نطف فاذا هو خصیم مبین
        ///والانعام خلقها لکم فیها دف ومنافع ومنها تاکلون
        ///ولکم فیها جمال حین تریحون وحین تسرحون
        ///وتحمل اثقالکم الى بلد لم تکونوا بالغیه الا بشق الانفس ان ربکم لروف رحیم
        ///والخیل والبغال والحمیر لترکبوها وزین ویخلق ما لا تعلمون
        ///وعلى الله قصد السبیل ومنها جائر ولو شا لهداکم اجمعین
        ///هو الذی  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _16 {
            get {
                return ResourceManager.GetString("_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سبحان الذی اسرى بعبده لیلا من المسجد الحرام الى المسجد الاقصى الذی بارکنا حوله لنریه من ایاتنا انه هو السمیع البصیر
        ///واتینا موسى الکتاب وجعلناه هدى لبنی اسرائیل الا تتخذوا من دونی وکیلا
        ///ذری من حملنا مع نوح انه کان عبدا شکورا
        ///وقضینا الى بنی اسرائیل فی الکتاب لتفسدن فی الارض مرتین ولتعلن علوا کبیرا
        ///فاذا جا وعد اولاهما بعثنا علیکم عبادا لنا اولی باس شدید فجاسوا خلال الدیار وکان وعدا مفعولا
        ///ثم رددنا لکم الکر علیهم وامددناکم باموال وبنین وجعلناکم اکثر نفیرا
        ///ان احسنتم احسنتم لانفسکم وان اسات [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _17 {
            get {
                return ResourceManager.GetString("_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الحمد لله الذی انزل على عبده الکتاب ولم یجعل له عوجا
        ///قیما لینذر باسا شدیدا من لدنه ویبشر المومنین الذین یعملون الصالحات ان لهم اجرا حسنا
        ///ماکثین فیه ابدا
        ///وینذر الذین قالوا اتخذ الله ولدا
        ///ما لهم به من علم ولا لابائهم کبرت کلم تخرج من افواههم ان یقولون الا کذبا
        ///فلعلک باخع نفسک على اثارهم ان لم یومنوا بهذا الحدیث اسفا
        ///انا جعلنا ما على الارض زین لها لنبلوهم ایهم احسن عملا
        ///وانا لجاعلون ما علیها صعیدا جرزا
        ///ام حسبت ان اصحاب الکهف والرقیم کانوا من ایاتنا عجبا
        ///اذ اوى الفتی الى الکهف فقالوا ربنا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _18 {
            get {
                return ResourceManager.GetString("_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم کهیعص
        ///ذکر رحمت ربک عبده زکریا
        ///اذ نادى ربه ندا خفیا
        ///قال رب انی وهن العظم منی واشتعل الراس شیبا ولم اکن بدعائک رب شقیا
        ///وانی خفت الموالی من ورائی وکانت امراتی عاقرا فهب لی من لدنک ولیا
        ///یرثنی ویرث من ال یعقوب واجعله رب رضیا
        ///یا زکریا انا نبشرک بغلام اسمه یحیى لم نجعل له من قبل سمیا
        ///قال رب انى یکون لی غلام وکانت امراتی عاقرا وقد بلغت من الکبر عتیا
        ///قال کذلک قال ربک هو علی هین وقد خلقتک من قبل ولم تک شیئا
        ///قال رب اجعل لی ای قال ایتک الا تکلم الناس ثلاث لیال سویا
        ///فخرج على قومه من المحراب فاوحى  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _19 {
            get {
                return ResourceManager.GetString("_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///ذلک الکتاب لا ریب فیه هدى للمتقین
        ///الذین یومنون بالغیب ویقیمون الصلا ومما رزقناهم ینفقون
        ///والذین یومنون بما انزل الیک وما انزل من قبلک وبالاخر هم یوقنون
        ///اولئک على هدى من ربهم واولئک هم المفلحون
        ///ان الذین کفروا سوا علیهم اانذرتهم ام لم تنذرهم لا یومنون
        ///ختم الله على قلوبهم وعلى سمعهم وعلى ابصارهم غشاو ولهم عذاب عظیم
        ///ومن الناس من یقول امنا بالله وبالیوم الاخر وما هم بمومنین
        ///یخادعون الله والذین امنوا وما یخدعون الا انفسهم وما یشعرون
        ///فی قلوبهم مرض فزادهم الله مرضا ولهم عذاب الیم بما کانوا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم طه
        ///ما انزلنا علیک القران لتشقى
        ///الا تذکر لمن یخشى
        ///تنزیلا ممن خلق الارض والسماوات العلى
        ///الرحمن على العرش استوى
        ///له ما فی السماوات وما فی الارض وما بینهما وما تحت الثرى
        ///وان تجهر بالقول فانه یعلم السر واخفى
        ///الله لا اله الا هو له الاسما الحسنى
        ///وهل اتاک حدیث موسى
        ///اذ راى نارا فقال لاهله امکثوا انی انست نارا لعلی اتیکم منها بقبس او اجد على النار هدى
        ///فلما اتاها نودی یا موسى
        ///انی انا ربک فاخلع نعلیک انک بالواد المقدس طوى
        ///وانا اخترتک فاستمع لما یوحى
        ///اننی انا الله لا اله الا انا فاعبدنی واقم الصلا  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _20 {
            get {
                return ResourceManager.GetString("_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اقترب للناس حسابهم وهم فی غفل معرضون
        ///ما یاتیهم من ذکر من ربهم محدث الا استمعوه وهم یلعبون
        ///لاهی قلوبهم واسروا النجوى الذین ظلموا هل هذا الا بشر مثلکم افتاتون السحر وانتم تبصرون
        ///قال ربی یعلم القول فی السما والارض وهو السمیع العلیم
        ///بل قالوا اضغاث احلام بل افتراه بل هو شاعر فلیاتنا بای کما ارسل الاولون
        ///ما امنت قبلهم من قری اهلکناها افهم یومنون
        ///وما ارسلنا قبلک الا رجالا نوحی الیهم فاسالوا اهل الذکر ان کنتم لا تعلمون
        ///وما جعلناهم جسدا لا یاکلون الطعام وما کانوا خالدین
        ///ثم صدقناهم الوعد فانجین [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _21 {
            get {
                return ResourceManager.GetString("_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها الناس اتقوا ربکم ان زلزل الساع شی عظیم
        ///یوم ترونها تذهل کل مرضع عما ارضعت وتضع کل ذات حمل حملها وترى الناس سکارى وما هم بسکارى ولکن عذاب الله شدید
        ///ومن الناس من یجادل فی الله بغیر علم ویتبع کل شیطان مرید
        ///کتب علیه انه من تولاه فانه یضله ویهدیه الى عذاب السعیر
        ///یا ایها الناس ان کنتم فی ریب من البعث فانا خلقناکم من تراب ثم من نطف ثم من علق ثم من مضغ مخلق وغیر مخلق لنبین لکم ونقر فی الارحام ما نشا الى اجل مسمى ثم نخرجکم طفلا ثم لتبلغوا اشدکم ومنکم من یتوفى ومنکم من یرد الى ارذل العمر [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _22 {
            get {
                return ResourceManager.GetString("_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قد افلح المومنون
        ///الذین هم فی صلاتهم خاشعون
        ///والذین هم عن اللغو معرضون
        ///والذین هم للزکا فاعلون
        ///والذین هم لفروجهم حافظون
        ///الا على ازواجهم او ما ملکت ایمانهم فانهم غیر ملومین
        ///فمن ابتغى ورا ذلک فاولئک هم العادون
        ///والذین هم لاماناتهم وعهدهم راعون
        ///والذین هم على صلواتهم یحافظون
        ///اولئک هم الوارثون
        ///الذین یرثون الفردوس هم فیها خالدون
        ///ولقد خلقنا الانسان من سلال من طین
        ///ثم جعلناه نطف فی قرار مکین
        ///ثم خلقنا النطف علق فخلقنا العلق مضغ فخلقنا المضغ عظاما فکسونا العظام لحما ثم انشاناه خلقا اخر فتبارک الله ا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _23 {
            get {
                return ResourceManager.GetString("_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سور انزلناها وفرضناها وانزلنا فیها ایات بینات لعلکم تذکرون
        ///الزانی والزانی فاجلدوا کل واحد منهما مائ جلد ولا تاخذکم بهما راف فی دین الله ان کنتم تومنون بالله والیوم الاخر ولیشهد عذابهما طائف من المومنین
        ///الزانی لا ینکح الا زانی او مشرک والزانی لا ینکحها الا زان او مشرک وحرم ذلک على المومنین
        ///والذین یرمون المحصنات ثم لم یاتوا باربع شهدا فاجلدوهم ثمانین جلد ولا تقبلوا لهم شهاد ابدا واولئک هم الفاسقون
        ///الا الذین تابوا من بعد ذلک واصلحوا فان الله غفور رحیم
        ///والذین یرمون ازواجهم ولم یکن لهم شهد [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _24 {
            get {
                return ResourceManager.GetString("_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم تبارک الذی نزل الفرقان على عبده لیکون للعالمین نذیرا
        ///الذی له ملک السماوات والارض ولم یتخذ ولدا ولم یکن له شریک فی الملک وخلق کل شی فقدره تقدیرا
        ///واتخذوا من دونه اله لا یخلقون شیئا وهم یخلقون ولا یملکون لانفسهم ضرا ولا نفعا ولا یملکون موتا ولا حیا ولا نشورا
        ///وقال الذین کفروا ان هذا الا افک افتراه واعانه علیه قوم اخرون فقد جاوا ظلما وزورا
        ///وقالوا اساطیر الاولین اکتتبها فهی تملى علیه بکر واصیلا
        ///قل انزله الذی یعلم السر فی السماوات والارض انه کان غفورا رحیما
        ///وقالوا مال هذا الرسول یاکل الطعام  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _25 {
            get {
                return ResourceManager.GetString("_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم طسم
        ///تلک ایات الکتاب المبین
        ///لعلک باخع نفسک الا یکونوا مومنین
        ///ان نشا ننزل علیهم من السما ای فظلت اعناقهم لها خاضعین
        ///وما یاتیهم من ذکر من الرحمن محدث الا کانوا عنه معرضین
        ///فقد کذبوا فسیاتیهم انبا ما کانوا به یستهزئون
        ///اولم یروا الى الارض کم انبتنا فیها من کل زوج کریم
        ///ان فی ذلک لای وما کان اکثرهم مومنین
        ///وان ربک لهو العزیز الرحیم
        ///واذ نادى ربک موسى ان ائت القوم الظالمین
        ///قوم فرعون الا یتقون
        ///قال رب انی اخاف ان یکذبون
        ///ویضیق صدری ولا ینطلق لسانی فارسل الى هارون
        ///ولهم علی ذنب فاخاف ان یقتلون
        ///قال کل [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _26 {
            get {
                return ResourceManager.GetString("_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم طس تلک ایات القران وکتاب مبین
        ///هدى وبشرى للمومنین
        ///الذین یقیمون الصلا ویوتون الزکا وهم بالاخر هم یوقنون
        ///ان الذین لا یومنون بالاخر زینا لهم اعمالهم فهم یعمهون
        ///اولئک الذین لهم سو العذاب وهم فی الاخر هم الاخسرون
        ///وانک لتلقى القران من لدن حکیم علیم
        ///اذ قال موسى لاهله انی انست نارا ساتیکم منها بخبر او اتیکم بشهاب قبس لعلکم تصطلون
        ///فلما جاها نودی ان بورک من فی النار ومن حولها وسبحان الله رب العالمین
        ///یا موسى انه انا الله العزیز الحکیم
        ///والق عصاک فلما راها تهتز کانها جان ولى مدبرا ولم یعقب یا موسى  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _27 {
            get {
                return ResourceManager.GetString("_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم طسم
        ///تلک ایات الکتاب المبین
        ///نتلو علیک من نبا موسى وفرعون بالحق لقوم یومنون
        ///ان فرعون علا فی الارض وجعل اهلها شیعا یستضعف طائف منهم یذبح ابناهم ویستحیی نساهم انه کان من المفسدین
        ///ونرید ان نمن على الذین استضعفوا فی الارض ونجعلهم ائم ونجعلهم الوارثین
        ///ونمکن لهم فی الارض ونری فرعون وهامان وجنودهما منهم ما کانوا یحذرون
        ///واوحینا الى ام موسى ان ارضعیه فاذا خفت علیه فالقیه فی الیم ولا تخافی ولا تحزنی انا رادوه الیک وجاعلوه من المرسلین
        ///فالتقطه ال فرعون لیکون لهم عدوا وحزنا ان فرعون وهامان وجنودهما  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _28 {
            get {
                return ResourceManager.GetString("_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///احسب الناس ان یترکوا ان یقولوا امنا وهم لا یفتنون
        ///ولقد فتنا الذین من قبلهم فلیعلمن الله الذین صدقوا ولیعلمن الکاذبین
        ///ام حسب الذین یعملون السیئات ان یسبقونا سا ما یحکمون
        ///من کان یرجو لقا الله فان اجل الله لات وهو السمیع العلیم
        ///ومن جاهد فانما یجاهد لنفسه ان الله لغنی عن العالمین
        ///والذین امنوا وعملوا الصالحات لنکفرن عنهم سیئاتهم ولنجزینهم احسن الذی کانوا یعملون
        ///ووصینا الانسان بوالدیه حسنا وان جاهداک لتشرک بی ما لیس لک به علم فلا تطعهما الی مرجعکم فانبئکم بما کنتم تعملون
        ///والذین امنوا وع [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _29 {
            get {
                return ResourceManager.GetString("_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///الله لا اله الا هو الحی القیوم
        ///نزل علیک الکتاب بالحق مصدقا لما بین یدیه وانزل التورا والانجیل
        ///من قبل هدى للناس وانزل الفرقان ان الذین کفروا بایات الله لهم عذاب شدید والله عزیز ذو انتقام
        ///ان الله لا یخفى علیه شی فی الارض ولا فی السما
        ///هو الذی یصورکم فی الارحام کیف یشا لا اله الا هو العزیز الحکیم
        ///هو الذی انزل علیک الکتاب منه ایات محکمات هن ام الکتاب واخر متشابهات فاما الذین فی قلوبهم زیغ فیتبعون ما تشابه منه ابتغا الفتن وابتغا تاویله وما یعلم تاویله الا الله والراسخون فی العلم یقولون  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///غلبت الروم
        ///فی ادنى الارض وهم من بعد غلبهم سیغلبون
        ///فی بضع سنین لله الامر من قبل ومن بعد ویومئذ یفرح المومنون
        ///بنصر الله ینصر من یشا وهو العزیز الرحیم
        ///وعد الله لا یخلف الله وعده ولکن اکثر الناس لا یعلمون
        ///یعلمون ظاهرا من الحیا الدنیا وهم عن الاخر هم غافلون
        ///اولم یتفکروا فی انفسهم ما خلق الله السماوات والارض وما بینهما الا بالحق واجل مسمى وان کثیرا من الناس بلقا ربهم لکافرون
        ///اولم یسیروا فی الارض فینظروا کیف کان عاقب الذین من قبلهم کانوا اشد منهم قو واثاروا الارض وعمروها اکثر مما عمروها  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _30 {
            get {
                return ResourceManager.GetString("_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///تلک ایات الکتاب الحکیم
        ///هدى ورحم للمحسنین
        ///الذین یقیمون الصلا ویوتون الزکا وهم بالاخر هم یوقنون
        ///اولئک على هدى من ربهم واولئک هم المفلحون
        ///ومن الناس من یشتری لهو الحدیث لیضل عن سبیل الله بغیر علم ویتخذها هزوا اولئک لهم عذاب مهین
        ///واذا تتلى علیه ایاتنا ولى مستکبرا کان لم یسمعها کان فی اذنیه وقرا فبشره بعذاب الیم
        ///ان الذین امنوا وعملوا الصالحات لهم جنات النعیم
        ///خالدین فیها وعد الله حقا وهو العزیز الحکیم
        ///خلق السماوات بغیر عمد ترونها والقى فی الارض رواسی ان تمید بکم وبث فیها من کل داب وانزلن [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _31 {
            get {
                return ResourceManager.GetString("_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم
        ///تنزیل الکتاب لا ریب فیه من رب العالمین
        ///ام یقولون افتراه بل هو الحق من ربک لتنذر قوما ما اتاهم من نذیر من قبلک لعلهم یهتدون
        ///الله الذی خلق السماوات والارض وما بینهما فی ست ایام ثم استوى على العرش ما لکم من دونه من ولی ولا شفیع افلا تتذکرون
        ///یدبر الامر من السما الى الارض ثم یعرج الیه فی یوم کان مقداره الف سن مما تعدون
        ///ذلک عالم الغیب والشهاد العزیز الرحیم
        ///الذی احسن کل شی خلقه وبدا خلق الانسان من طین
        ///ثم جعل نسله من سلال من ما مهین
        ///ثم سواه ونفخ فیه من روحه وجعل لکم السمع والابصار والافئد [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _32 {
            get {
                return ResourceManager.GetString("_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها النبی اتق الله ولا تطع الکافرین والمنافقین ان الله کان علیما حکیما
        ///واتبع ما یوحى الیک من ربک ان الله کان بما تعملون خبیرا
        ///وتوکل على الله وکفى بالله وکیلا
        ///ما جعل الله لرجل من قلبین فی جوفه وما جعل ازواجکم اللائی تظاهرون منهن امهاتکم وما جعل ادعیاکم ابناکم ذلکم قولکم بافواهکم والله یقول الحق وهو یهدی السبیل
        ///ادعوهم لابائهم هو اقسط عند الله فان لم تعلموا اباهم فاخوانکم فی الدین وموالیکم ولیس علیکم جناح فیما اخطاتم به ولکن ما تعمدت قلوبکم وکان الله غفورا رحیما
        ///النبی اولى بالمومنین  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _33 {
            get {
                return ResourceManager.GetString("_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الحمد لله الذی له ما فی السماوات وما فی الارض وله الحمد فی الاخر وهو الحکیم الخبیر
        ///یعلم ما یلج فی الارض وما یخرج منها وما ینزل من السما وما یعرج فیها وهو الرحیم الغفور
        ///وقال الذین کفروا لا تاتینا الساع قل بلى وربی لتاتینکم عالم الغیب لا یعزب عنه مثقال ذر فی السماوات ولا فی الارض ولا اصغر من ذلک ولا اکبر الا فی کتاب مبین
        ///لیجزی الذین امنوا وعملوا الصالحات اولئک لهم مغفر ورزق کریم
        ///والذین سعوا فی ایاتنا معاجزین اولئک لهم عذاب من رجز الیم
        ///ویرى الذین اوتوا العلم الذی انزل الیک من ربک هو الحق [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _34 {
            get {
                return ResourceManager.GetString("_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الحمد لله فاطر السماوات والارض جاعل الملائک رسلا اولی اجنح مثنى وثلاث ورباع یزید فی الخلق ما یشا ان الله على کل شی قدیر
        ///ما یفتح الله للناس من رحم فلا ممسک لها وما یمسک فلا مرسل له من بعده وهو العزیز الحکیم
        ///یا ایها الناس اذکروا نعمت الله علیکم هل من خالق غیر الله یرزقکم من السما والارض لا اله الا هو فانى توفکون
        ///وان یکذبوک فقد کذبت رسل من قبلک والى الله ترجع الامور
        ///یا ایها الناس ان وعد الله حق فلا تغرنکم الحیا الدنیا ولا یغرنکم بالله الغرور
        ///ان الشیطان لکم عدو فاتخذوه عدوا انما یدعو حزبه [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _35 {
            get {
                return ResourceManager.GetString("_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یس
        ///والقران الحکیم
        ///انک لمن المرسلین
        ///على صراط مستقیم
        ///تنزیل العزیز الرحیم
        ///لتنذر قوما ما انذر اباوهم فهم غافلون
        ///لقد حق القول على اکثرهم فهم لا یومنون
        ///انا جعلنا فی اعناقهم اغلالا فهی الى الاذقان فهم مقمحون
        ///وجعلنا من بین ایدیهم سدا ومن خلفهم سدا فاغشیناهم فهم لا یبصرون
        ///وسوا علیهم اانذرتهم ام لم تنذرهم لا یومنون
        ///انما تنذر من اتبع الذکر وخشی الرحمن بالغیب فبشره بمغفر واجر کریم
        ///انا نحن نحیی الموتى ونکتب ما قدموا واثارهم وکل شی احصیناه فی امام مبین
        ///واضرب لهم مثلا اصحاب القری اذ جاها المرسلون
        ///اذ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _36 {
            get {
                return ResourceManager.GetString("_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والصافات صفا
        ///فالزاجرات زجرا
        ///فالتالیات ذکرا
        ///ان الهکم لواحد
        ///رب السماوات والارض وما بینهما ورب المشارق
        ///انا زینا السما الدنیا بزین الکواکب
        ///وحفظا من کل شیطان مارد
        ///لا یسمعون الى الملا الاعلى ویقذفون من کل جانب
        ///دحورا ولهم عذاب واصب
        ///الا من خطف الخطف فاتبعه شهاب ثاقب
        ///فاستفتهم اهم اشد خلقا ام من خلقنا انا خلقناهم من طین لازب
        ///بل عجبت ویسخرون
        ///واذا ذکروا لا یذکرون
        ///واذا راوا ای یستسخرون
        ///وقالوا ان هذا الا سحر مبین
        ///ااذا متنا وکنا ترابا وعظاما اانا لمبعوثون
        ///اواباونا الاولون
        ///قل نعم وانتم داخرون
        ///فانما ه [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _37 {
            get {
                return ResourceManager.GetString("_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ص والقران ذی الذکر
        ///بل الذین کفروا فی عز وشقاق
        ///کم اهلکنا من قبلهم من قرن فنادوا ولات حین مناص
        ///وعجبوا ان جاهم منذر منهم وقال الکافرون هذا ساحر کذاب
        ///اجعل الاله الها واحدا ان هذا لشی عجاب
        ///وانطلق الملا منهم ان امشوا واصبروا على الهتکم ان هذا لشی یراد
        ///ما سمعنا بهذا فی المل الاخر ان هذا الا اختلاق
        ///اانزل علیه الذکر من بیننا بل هم فی شک من ذکری بل لما یذوقوا عذاب
        ///ام عندهم خزائن رحم ربک العزیز الوهاب
        ///ام لهم ملک السماوات والارض وما بینهما فلیرتقوا فی الاسباب
        ///جند ما هنالک مهزوم من الاحزاب
        ///کذبت قب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _38 {
            get {
                return ResourceManager.GetString("_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم تنزیل الکتاب من الله العزیز الحکیم
        ///انا انزلنا الیک الکتاب بالحق فاعبد الله مخلصا له الدین
        ///الا لله الدین الخالص والذین اتخذوا من دونه اولیا ما نعبدهم الا لیقربونا الى الله زلفى ان الله یحکم بینهم فی ما هم فیه یختلفون ان الله لا یهدی من هو کاذب کفار
        ///لو اراد الله ان یتخذ ولدا لاصطفى مما یخلق ما یشا سبحانه هو الله الواحد القهار
        ///خلق السماوات والارض بالحق یکور اللیل على النهار ویکور النهار على اللیل وسخر الشمس والقمر کل یجری لاجل مسمى الا هو العزیز الغفار
        ///خلقکم من نفس واحد ثم جعل منها زوجها [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _39 {
            get {
                return ResourceManager.GetString("_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها الناس اتقوا ربکم الذی خلقکم من نفس واحد وخلق منها زوجها وبث منهما رجالا کثیرا ونسا واتقوا الله الذی تسالون به والارحام ان الله کان علیکم رقیبا
        ///واتوا الیتامى اموالهم ولا تتبدلوا الخبیث بالطیب ولا تاکلوا اموالهم الى اموالکم انه کان حوبا کبیرا
        ///وان خفتم الا تقسطوا فی الیتامى فانکحوا ما طاب لکم من النسا مثنى وثلاث ورباع فان خفتم الا تعدلوا فواحد او ما ملکت ایمانکم ذلک ادنى الا تعولوا
        ///واتوا النسا صدقاتهن نحل فان طبن لکم عن شی منه نفسا فکلوه هنیئا مریئا
        ///ولا توتوا السفها اموالکم التی  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///تنزیل الکتاب من الله العزیز العلیم
        ///غافر الذنب وقابل التوب شدید العقاب ذی الطول لا اله الا هو الیه المصیر
        ///ما یجادل فی ایات الله الا الذین کفروا فلا یغررک تقلبهم فی البلاد
        ///کذبت قبلهم قوم نوح والاحزاب من بعدهم وهمت کل ام برسولهم لیاخذوه وجادلوا بالباطل لیدحضوا به الحق فاخذتهم فکیف کان عقاب
        ///وکذلک حقت کلمت ربک على الذین کفروا انهم اصحاب النار
        ///الذین یحملون العرش ومن حوله یسبحون بحمد ربهم ویومنون به ویستغفرون للذین امنوا ربنا وسعت کل شی رحم وعلما فاغفر للذین تابوا واتبعوا سبیلک وقهم عذاب  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _40 {
            get {
                return ResourceManager.GetString("_40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///تنزیل من الرحمن الرحیم
        ///کتاب فصلت ایاته قرانا عربیا لقوم یعلمون
        ///بشیرا ونذیرا فاعرض اکثرهم فهم لا یسمعون
        ///وقالوا قلوبنا فی اکن مما تدعونا الیه وفی اذاننا وقر ومن بیننا وبینک حجاب فاعمل اننا عاملون
        ///قل انما انا بشر مثلکم یوحى الی انما الهکم اله واحد فاستقیموا الیه واستغفروه وویل للمشرکین
        ///الذین لا یوتون الزکا وهم بالاخر هم کافرون
        ///ان الذین امنوا وعملوا الصالحات لهم اجر غیر ممنون
        ///قل ائنکم لتکفرون بالذی خلق الارض فی یومین وتجعلون له اندادا ذلک رب العالمین
        ///وجعل فیها رواسی من فوقها وبارک فیها [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _41 {
            get {
                return ResourceManager.GetString("_41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///عسق
        ///کذلک یوحی الیک والى الذین من قبلک الله العزیز الحکیم
        ///له ما فی السماوات وما فی الارض وهو العلی العظیم
        ///تکاد السماوات یتفطرن من فوقهن والملائک یسبحون بحمد ربهم ویستغفرون لمن فی الارض الا ان الله هو الغفور الرحیم
        ///والذین اتخذوا من دونه اولیا الله حفیظ علیهم وما انت علیهم بوکیل
        ///وکذلک اوحینا الیک قرانا عربیا لتنذر ام القرى ومن حولها وتنذر یوم الجمع لا ریب فیه فریق فی الجن وفریق فی السعیر
        ///ولو شا الله لجعلهم ام واحد ولکن یدخل من یشا فی رحمته والظالمون ما لهم من ولی ولا نصیر
        ///ام اتخذوا من [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _42 {
            get {
                return ResourceManager.GetString("_42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///والکتاب المبین
        ///انا جعلناه قرانا عربیا لعلکم تعقلون
        ///وانه فی ام الکتاب لدینا لعلی حکیم
        ///افنضرب عنکم الذکر صفحا ان کنتم قوما مسرفین
        ///وکم ارسلنا من نبی فی الاولین
        ///وما یاتیهم من نبی الا کانوا به یستهزئون
        ///فاهلکنا اشد منهم بطشا ومضى مثل الاولین
        ///ولئن سالتهم من خلق السماوات والارض لیقولن خلقهن العزیز العلیم
        ///الذی جعل لکم الارض مهدا وجعل لکم فیها سبلا لعلکم تهتدون
        ///والذی نزل من السما ما بقدر فانشرنا به بلد میتا کذلک تخرجون
        ///والذی خلق الازواج کلها وجعل لکم من الفلک والانعام ما ترکبون
        ///لتستووا على ظ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _43 {
            get {
                return ResourceManager.GetString("_43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///والکتاب المبین
        ///انا انزلناه فی لیل مبارک انا کنا منذرین
        ///فیها یفرق کل امر حکیم
        ///امرا من عندنا انا کنا مرسلین
        ///رحم من ربک انه هو السمیع العلیم
        ///رب السماوات والارض وما بینهما ان کنتم موقنین
        ///لا اله الا هو یحیی ویمیت ربکم ورب ابائکم الاولین
        ///بل هم فی شک یلعبون
        ///فارتقب یوم تاتی السما بدخان مبین
        ///یغشى الناس هذا عذاب الیم
        ///ربنا اکشف عنا العذاب انا مومنون
        ///انى لهم الذکرى وقد جاهم رسول مبین
        ///ثم تولوا عنه وقالوا معلم مجنون
        ///انا کاشفو العذاب قلیلا انکم عائدون
        ///یوم نبطش البطش الکبرى انا منتقمون
        ///ولقد فتنا ق [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _44 {
            get {
                return ResourceManager.GetString("_44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///تنزیل الکتاب من الله العزیز الحکیم
        ///ان فی السماوات والارض لایات للمومنین
        ///وفی خلقکم وما یبث من داب ایات لقوم یوقنون
        ///واختلاف اللیل والنهار وما انزل الله من السما من رزق فاحیا به الارض بعد موتها وتصریف الریاح ایات لقوم یعقلون
        ///تلک ایات الله نتلوها علیک بالحق فبای حدیث بعد الله وایاته یومنون
        ///ویل لکل افاک اثیم
        ///یسمع ایات الله تتلى علیه ثم یصر مستکبرا کان لم یسمعها فبشره بعذاب الیم
        ///واذا علم من ایاتنا شیئا اتخذها هزوا اولئک لهم عذاب مهین
        ///من ورائهم جهنم ولا یغنی عنهم ما کسبوا شیئا ولا ما اتخذ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _45 {
            get {
                return ResourceManager.GetString("_45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم حم
        ///تنزیل الکتاب من الله العزیز الحکیم
        ///ما خلقنا السماوات والارض وما بینهما الا بالحق واجل مسمى والذین کفروا عما انذروا معرضون
        ///قل ارایتم ما تدعون من دون الله ارونی ماذا خلقوا من الارض ام لهم شرک فی السماوات ائتونی بکتاب من قبل هذا او اثار من علم ان کنتم صادقین
        ///ومن اضل ممن یدعو من دون الله من لا یستجیب له الى یوم القیام وهم عن دعائهم غافلون
        ///واذا حشر الناس کانوا لهم اعدا وکانوا بعبادتهم کافرین
        ///واذا تتلى علیهم ایاتنا بینات قال الذین کفروا للحق لما جاهم هذا سحر مبین
        ///ام یقولون افتراه قل ان ا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _46 {
            get {
                return ResourceManager.GetString("_46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الذین کفروا وصدوا عن سبیل الله اضل اعمالهم
        ///والذین امنوا وعملوا الصالحات وامنوا بما نزل على محمد وهو الحق من ربهم کفر عنهم سیئاتهم واصلح بالهم
        ///ذلک بان الذین کفروا اتبعوا الباطل وان الذین امنوا اتبعوا الحق من ربهم کذلک یضرب الله للناس امثالهم
        ///فاذا لقیتم الذین کفروا فضرب الرقاب حتى اذا اثخنتموهم فشدوا الوثاق فاما منا بعد واما فدا حتى تضع الحرب اوزارها ذلک ولو یشا الله لانتصر منهم ولکن لیبلو بعضکم ببعض والذین قتلوا فی سبیل الله فلن یضل اعمالهم
        ///سیهدیهم ویصلح بالهم
        ///ویدخلهم الجن عرفها لهم
        ///یا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _47 {
            get {
                return ResourceManager.GetString("_47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم انا فتحنا لک فتحا مبینا
        ///لیغفر لک الله ما تقدم من ذنبک وما تاخر ویتم نعمته علیک ویهدیک صراطا مستقیما
        ///وینصرک الله نصرا عزیزا
        ///هو الذی انزل السکین فی قلوب المومنین لیزدادوا ایمانا مع ایمانهم ولله جنود السماوات والارض وکان الله علیما حکیما
        ///لیدخل المومنین والمومنات جنات تجری من تحتها الانهار خالدین فیها ویکفر عنهم سیئاتهم وکان ذلک عند الله فوزا عظیما
        ///ویعذب المنافقین والمنافقات والمشرکین والمشرکات الظانین بالله ظن السو علیهم دائر السو وغضب الله علیهم ولعنهم واعد لهم جهنم وسات مصیرا
        ///ولله جنود [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _48 {
            get {
                return ResourceManager.GetString("_48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها الذین امنوا لا تقدموا بین یدی الله ورسوله واتقوا الله ان الله سمیع علیم
        ///یا ایها الذین امنوا لا ترفعوا اصواتکم فوق صوت النبی ولا تجهروا له بالقول کجهر بعضکم لبعض ان تحبط اعمالکم وانتم لا تشعرون
        ///ان الذین یغضون اصواتهم عند رسول الله اولئک الذین امتحن الله قلوبهم للتقوى لهم مغفر واجر عظیم
        ///ان الذین ینادونک من ورا الحجرات اکثرهم لا یعقلون
        ///ولو انهم صبروا حتى تخرج الیهم لکان خیرا لهم والله غفور رحیم
        ///یا ایها الذین امنوا ان جاکم فاسق بنبا فتبینوا ان تصیبوا قوما بجهال فتصبحوا على ما فعلت [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _49 {
            get {
                return ResourceManager.GetString("_49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها الذین امنوا اوفوا بالعقود احلت لکم بهیم الانعام الا ما یتلى علیکم غیر محلی الصید وانتم حرم ان الله یحکم ما یرید
        ///یا ایها الذین امنوا لا تحلوا شعائر الله ولا الشهر الحرام ولا الهدی ولا القلائد ولا امین البیت الحرام یبتغون فضلا من ربهم ورضوانا واذا حللتم فاصطادوا ولا یجرمنکم شنان قوم ان صدوکم عن المسجد الحرام ان تعتدوا وتعاونوا على البر والتقوى ولا تعاونوا على الاثم والعدوان واتقوا الله ان الله شدید العقاب
        ///حرمت علیکم المیت والدم ولحم الخنزیر وما اهل لغیر الله به والمنخنق والموقوذ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ق والقران المجید
        ///بل عجبوا ان جاهم منذر منهم فقال الکافرون هذا شی عجیب
        ///ااذا متنا وکنا ترابا ذلک رجع بعید
        ///قد علمنا ما تنقص الارض منهم وعندنا کتاب حفیظ
        ///بل کذبوا بالحق لما جاهم فهم فی امر مریج
        ///افلم ینظروا الى السما فوقهم کیف بنیناها وزیناها وما لها من فروج
        ///والارض مددناها والقینا فیها رواسی وانبتنا فیها من کل زوج بهیج
        ///تبصر وذکرى لکل عبد منیب
        ///ونزلنا من السما ما مبارکا فانبتنا به جنات وحب الحصید
        ///والنخل باسقات لها طلع نضید
        ///رزقا للعباد واحیینا به بلد میتا کذلک الخروج
        ///کذبت قبلهم قوم نوح واصحاب  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _50 {
            get {
                return ResourceManager.GetString("_50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والذاریات ذروا
        ///فالحاملات وقرا
        ///فالجاریات یسرا
        ///فالمقسمات امرا
        ///انما توعدون لصادق
        ///وان الدین لواقع
        ///والسما ذات الحبک
        ///انکم لفی قول مختلف
        ///یوفک عنه من افک
        ///قتل الخراصون
        ///الذین هم فی غمر ساهون
        ///یسالون ایان یوم الدین
        ///یوم هم على النار یفتنون
        ///ذوقوا فتنتکم هذا الذی کنتم به تستعجلون
        ///ان المتقین فی جنات وعیون
        ///اخذین ما اتاهم ربهم انهم کانوا قبل ذلک محسنین
        ///کانوا قلیلا من اللیل ما یهجعون
        ///وبالاسحار هم یستغفرون
        ///وفی اموالهم حق للسائل والمحروم
        ///وفی الارض ایات للموقنین
        ///وفی انفسکم افلا تبصرون
        ///وفی السما رزقکم وما ت [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _51 {
            get {
                return ResourceManager.GetString("_51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والطور
        ///وکتاب مسطور
        ///فی رق منشور
        ///والبیت المعمور
        ///والسقف المرفوع
        ///والبحر المسجور
        ///ان عذاب ربک لواقع
        ///ما له من دافع
        ///یوم تمور السما مورا
        ///وتسیر الجبال سیرا
        ///فویل یومئذ للمکذبین
        ///الذین هم فی خوض یلعبون
        ///یوم یدعون الى نار جهنم دعا
        ///هذه النار التی کنتم بها تکذبون
        ///افسحر هذا ام انتم لا تبصرون
        ///اصلوها فاصبروا او لا تصبروا سوا علیکم انما تجزون ما کنتم تعملون
        ///ان المتقین فی جنات ونعیم
        ///فاکهین بما اتاهم ربهم ووقاهم ربهم عذاب الجحیم
        ///کلوا واشربوا هنیئا بما کنتم تعملون
        ///متکئین على سرر مصفوف وزوجناهم بحور عین
        ///والذی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _52 {
            get {
                return ResourceManager.GetString("_52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والنجم اذا هوى
        ///ما ضل صاحبکم وما غوى
        ///وما ینطق عن الهوى
        ///ان هو الا وحی یوحى
        ///علمه شدید القوى
        ///ذو مر فاستوى
        ///وهو بالافق الاعلى
        ///ثم دنا فتدلى
        ///فکان قاب قوسین او ادنى
        ///فاوحى الى عبده ما اوحى
        ///ما کذب الفواد ما راى
        ///افتمارونه على ما یرى
        ///ولقد راه نزل اخرى
        ///عند سدر المنتهى
        ///عندها جن الماوى
        ///اذ یغشى السدر ما یغشى
        ///ما زاغ البصر وما طغى
        ///لقد راى من ایات ربه الکبرى
        ///افرایتم اللات والعزى
        ///ومنا الثالث الاخرى
        ///الکم الذکر وله الانثى
        ///تلک اذا قسم ضیزى
        ///ان هی الا اسما سمیتموها انتم واباوکم ما انزل الله بها من سلطان ان یتب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _53 {
            get {
                return ResourceManager.GetString("_53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اقتربت الساع وانشق القمر
        ///وان یروا ای یعرضوا ویقولوا سحر مستمر
        ///وکذبوا واتبعوا اهواهم وکل امر مستقر
        ///ولقد جاهم من الانبا ما فیه مزدجر
        ///حکم بالغ فما تغن النذر
        ///فتول عنهم یوم یدع الداع الى شی نکر
        ///خشعا ابصارهم یخرجون من الاجداث کانهم جراد منتشر
        ///مهطعین الى الداع یقول الکافرون هذا یوم عسر
        ///کذبت قبلهم قوم نوح فکذبوا عبدنا وقالوا مجنون وازدجر
        ///فدعا ربه انی مغلوب فانتصر
        ///ففتحنا ابواب السما بما منهمر
        ///وفجرنا الارض عیونا فالتقى الما على امر قد قدر
        ///وحملناه على ذات الواح ودسر
        ///تجری باعیننا جزا لمن کان کفر
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _54 {
            get {
                return ResourceManager.GetString("_54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الرحمن
        ///علم القران
        ///خلق الانسان
        ///علمه البیان
        ///الشمس والقمر بحسبان
        ///والنجم والشجر یسجدان
        ///والسما رفعها ووضع المیزان
        ///الا تطغوا فی المیزان
        ///واقیموا الوزن بالقسط ولا تخسروا المیزان
        ///والارض وضعها للانام
        ///فیها فاکه والنخل ذات الاکمام
        ///والحب ذو العصف والریحان
        ///فبای الا ربکما تکذبان
        ///خلق الانسان من صلصال کالفخار
        ///وخلق الجان من مارج من نار
        ///فبای الا ربکما تکذبان
        ///رب المشرقین ورب المغربین
        ///فبای الا ربکما تکذبان
        ///مرج البحرین یلتقیان
        ///بینهما برزخ لا یبغیان
        ///فبای الا ربکما تکذبان
        ///یخرج منهما اللولو والمرجان
        ///فبای الا  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _55 {
            get {
                return ResourceManager.GetString("_55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا وقعت الواقع
        ///لیس لوقعتها کاذب
        ///خافض رافع
        ///اذا رجت الارض رجا
        ///وبست الجبال بسا
        ///فکانت هبا منبثا
        ///وکنتم ازواجا ثلاث
        ///فاصحاب المیمن ما اصحاب المیمن
        ///واصحاب المشام ما اصحاب المشام
        ///والسابقون السابقون
        ///اولئک المقربون
        ///فی جنات النعیم
        ///ثل من الاولین
        ///وقلیل من الاخرین
        ///على سرر موضون
        ///متکئین علیها متقابلین
        ///یطوف علیهم ولدان مخلدون
        ///باکواب واباریق وکاس من معین
        ///لا یصدعون عنها ولا ینزفون
        ///وفاکه مما یتخیرون
        ///ولحم طیر مما یشتهون
        ///وحور عین
        ///کامثال اللولو المکنون
        ///جزا بما کانوا یعملون
        ///لا یسمعون فیها لغوا ولا تاثیما
        ///الا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _56 {
            get {
                return ResourceManager.GetString("_56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سبح لله ما فی السماوات والارض وهو العزیز الحکیم
        ///له ملک السماوات والارض یحیی ویمیت وهو على کل شی قدیر
        ///هو الاول والاخر والظاهر والباطن وهو بکل شی علیم
        ///هو الذی خلق السماوات والارض فی ست ایام ثم استوى على العرش یعلم ما یلج فی الارض وما یخرج منها وما ینزل من السما وما یعرج فیها وهو معکم این ما کنتم والله بما تعملون بصیر
        ///له ملک السماوات والارض والى الله ترجع الامور
        ///یولج اللیل فی النهار ویولج النهار فی اللیل وهو علیم بذات الصدور
        ///امنوا بالله ورسوله وانفقوا مما جعلکم مستخلفین فیه فالذین امنوا  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _57 {
            get {
                return ResourceManager.GetString("_57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قد سمع الله قول التی تجادلک فی زوجها وتشتکی الى الله والله یسمع تحاورکما ان الله سمیع بصیر
        ///الذین یظاهرون منکم من نسائهم ما هن امهاتهم ان امهاتهم الا اللائی ولدنهم وانهم لیقولون منکرا من القول وزورا وان الله لعفو غفور
        ///والذین یظاهرون من نسائهم ثم یعودون لما قالوا فتحریر رقب من قبل ان یتماسا ذلکم توعظون به والله بما تعملون خبیر
        ///فمن لم یجد فصیام شهرین متتابعین من قبل ان یتماسا فمن لم یستطع فاطعام ستین مسکینا ذلک لتومنوا بالله ورسوله وتلک حدود الله وللکافرین عذاب الیم
        ///ان الذین یحادون الله  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _58 {
            get {
                return ResourceManager.GetString("_58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سبح لله ما فی السماوات وما فی الارض وهو العزیز الحکیم
        ///هو الذی اخرج الذین کفروا من اهل الکتاب من دیارهم لاول الحشر ما ظننتم ان یخرجوا وظنوا انهم مانعتهم حصونهم من الله فاتاهم الله من حیث لم یحتسبوا وقذف فی قلوبهم الرعب یخربون بیوتهم بایدیهم وایدی المومنین فاعتبروا یا اولی الابصار
        ///ولولا ان کتب الله علیهم الجلا لعذبهم فی الدنیا ولهم فی الاخر عذاب النار
        ///ذلک بانهم شاقوا الله ورسوله ومن یشاق الله فان الله شدید العقاب
        ///ما قطعتم من لین او ترکتموها قائم على اصولها فباذن الله ولیخزی الفاسقین
        ///وما [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _59 {
            get {
                return ResourceManager.GetString("_59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الحمد لله الذی خلق السماوات والارض وجعل الظلمات والنور ثم الذین کفروا بربهم یعدلون
        ///هو الذی خلقکم من طین ثم قضى اجلا واجل مسمى عنده ثم انتم تمترون
        ///وهو الله فی السماوات وفی الارض یعلم سرکم وجهرکم ویعلم ما تکسبون
        ///وما تاتیهم من ای من ایات ربهم الا کانوا عنها معرضین
        ///فقد کذبوا بالحق لما جاهم فسوف یاتیهم انبا ما کانوا به یستهزئون
        ///الم یروا کم اهلکنا من قبلهم من قرن مکناهم فی الارض ما لم نمکن لکم وارسلنا السما علیهم مدرارا وجعلنا الانهار تجری من تحتهم فاهلکناهم بذنوبهم وانشانا من بعدهم قرنا اخ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها الذین امنوا لا تتخذوا عدوی وعدوکم اولیا تلقون الیهم بالمود وقد کفروا بما جاکم من الحق یخرجون الرسول وایاکم ان تومنوا بالله ربکم ان کنتم خرجتم جهادا فی سبیلی وابتغا مرضاتی تسرون الیهم بالمود وانا اعلم بما اخفیتم وما اعلنتم ومن یفعله منکم فقد ضل سوا السبیل
        ///ان یثقفوکم یکونوا لکم اعدا ویبسطوا الیکم ایدیهم والسنتهم بالسو وودوا لو تکفرون
        ///لن تنفعکم ارحامکم ولا اولادکم یوم القیام یفصل بینکم والله بما تعملون بصیر
        ///قد کانت لکم اسو حسن فی ابراهیم والذین معه اذ قالوا لقومهم انا برا منکم وم [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _60 {
            get {
                return ResourceManager.GetString("_60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سبح لله ما فی السماوات وما فی الارض وهو العزیز الحکیم
        ///یا ایها الذین امنوا لم تقولون ما لا تفعلون
        ///کبر مقتا عند الله ان تقولوا ما لا تفعلون
        ///ان الله یحب الذین یقاتلون فی سبیله صفا کانهم بنیان مرصوص
        ///واذ قال موسى لقومه یا قوم لم توذوننی وقد تعلمون انی رسول الله الیکم فلما زاغوا ازاغ الله قلوبهم والله لا یهدی القوم الفاسقین
        ///واذ قال عیسى ابن مریم یا بنی اسرائیل انی رسول الله الیکم مصدقا لما بین یدی من التورا ومبشرا برسول یاتی من بعدی اسمه احمد فلما جاهم بالبینات قالوا هذا سحر مبین
        ///ومن اظلم م [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _61 {
            get {
                return ResourceManager.GetString("_61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یسبح لله ما فی السماوات وما فی الارض الملک القدوس العزیز الحکیم
        ///هو الذی بعث فی الامیین رسولا منهم یتلو علیهم ایاته ویزکیهم ویعلمهم الکتاب والحکم وان کانوا من قبل لفی ضلال مبین
        ///واخرین منهم لما یلحقوا بهم وهو العزیز الحکیم
        ///ذلک فضل الله یوتیه من یشا والله ذو الفضل العظیم
        ///مثل الذین حملوا التورا ثم لم یحملوها کمثل الحمار یحمل اسفارا بئس مثل القوم الذین کذبوا بایات الله والله لا یهدی القوم الظالمین
        ///قل یا ایها الذین هادوا ان زعمتم انکم اولیا لله من دون الناس فتمنوا الموت ان کنتم صادقین
        ///ولا ی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _62 {
            get {
                return ResourceManager.GetString("_62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا جاک المنافقون قالوا نشهد انک لرسول الله والله یعلم انک لرسوله والله یشهد ان المنافقین لکاذبون
        ///اتخذوا ایمانهم جن فصدوا عن سبیل الله انهم سا ما کانوا یعملون
        ///ذلک بانهم امنوا ثم کفروا فطبع على قلوبهم فهم لا یفقهون
        ///واذا رایتهم تعجبک اجسامهم وان یقولوا تسمع لقولهم کانهم خشب مسند یحسبون کل صیح علیهم هم العدو فاحذرهم قاتلهم الله انى یوفکون
        ///واذا قیل لهم تعالوا یستغفر لکم رسول الله لووا روسهم ورایتهم یصدون وهم مستکبرون
        ///سوا علیهم استغفرت لهم ام لم تستغفر لهم لن یغفر الله لهم ان الله لا یهدی  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _63 {
            get {
                return ResourceManager.GetString("_63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یسبح لله ما فی السماوات وما فی الارض له الملک وله الحمد وهو على کل شی قدیر
        ///هو الذی خلقکم فمنکم کافر ومنکم مومن والله بما تعملون بصیر
        ///خلق السماوات والارض بالحق وصورکم فاحسن صورکم والیه المصیر
        ///یعلم ما فی السماوات والارض ویعلم ما تسرون وما تعلنون والله علیم بذات الصدور
        ///الم یاتکم نبا الذین کفروا من قبل فذاقوا وبال امرهم ولهم عذاب الیم
        ///ذلک بانه کانت تاتیهم رسلهم بالبینات فقالوا ابشر یهدوننا فکفروا وتولوا واستغنى الله والله غنی حمید
        ///زعم الذین کفروا ان لن یبعثوا قل بلى وربی لتبعثن ثم لتنبون  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _64 {
            get {
                return ResourceManager.GetString("_64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها النبی اذا طلقتم النسا فطلقوهن لعدتهن واحصوا العد واتقوا الله ربکم لا تخرجوهن من بیوتهن ولا یخرجن الا ان یاتین بفاحش مبین وتلک حدود الله ومن یتعد حدود الله فقد ظلم نفسه لا تدری لعل الله یحدث بعد ذلک امرا
        ///فاذا بلغن اجلهن فامسکوهن بمعروف او فارقوهن بمعروف واشهدوا ذوی عدل منکم واقیموا الشهاد لله ذلکم یوعظ به من کان یومن بالله والیوم الاخر ومن یتق الله یجعل له مخرجا
        ///ویرزقه من حیث لا یحتسب ومن یتوکل على الله فهو حسبه ان الله بالغ امره قد جعل الله لکل شی قدرا
        ///واللائی یئسن من المحیض م [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _65 {
            get {
                return ResourceManager.GetString("_65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها النبی لم تحرم ما احل الله لک تبتغی مرضات ازواجک والله غفور رحیم
        ///قد فرض الله لکم تحل ایمانکم والله مولاکم وهو العلیم الحکیم
        ///واذ اسر النبی الى بعض ازواجه حدیثا فلما نبات به واظهره الله علیه عرف بعضه واعرض عن بعض فلما نباها به قالت من انباک هذا قال نبانی العلیم الخبیر
        ///ان تتوبا الى الله فقد صغت قلوبکما وان تظاهرا علیه فان الله هو مولاه وجبریل وصالح المومنین والملائک بعد ذلک ظهیر
        ///عسى ربه ان طلقکن ان یبدله ازواجا خیرا منکن مسلمات مومنات قانتات تائبات عابدات سائحات ثیبات وابکارا
        ///یا ا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _66 {
            get {
                return ResourceManager.GetString("_66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم تبارک الذی بیده الملک وهو على کل شی قدیر
        ///الذی خلق الموت والحیا لیبلوکم ایکم احسن عملا وهو العزیز الغفور
        ///الذی خلق سبع سماوات طباقا ما ترى فی خلق الرحمن من تفاوت فارجع البصر هل ترى من فطور
        ///ثم ارجع البصر کرتین ینقلب الیک البصر خاسئا وهو حسیر
        ///ولقد زینا السما الدنیا بمصابیح وجعلناها رجوما للشیاطین واعتدنا لهم عذاب السعیر
        ///وللذین کفروا بربهم عذاب جهنم وبئس المصیر
        ///اذا القوا فیها سمعوا لها شهیقا وهی تفور
        ///تکاد تمیز من الغیظ کلما القی فیها فوج سالهم خزنتها الم یاتکم نذیر
        ///قالوا بلى قد جانا نذیر ف [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _67 {
            get {
                return ResourceManager.GetString("_67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ن والقلم وما یسطرون
        ///ما انت بنعم ربک بمجنون
        ///وان لک لاجرا غیر ممنون
        ///وانک لعلى خلق عظیم
        ///فستبصر ویبصرون
        ///باییکم المفتون
        ///ان ربک هو اعلم بمن ضل عن سبیله وهو اعلم بالمهتدین
        ///فلا تطع المکذبین
        ///ودوا لو تدهن فیدهنون
        ///ولا تطع کل حلاف مهین
        ///هماز مشا بنمیم
        ///مناع للخیر معتد اثیم
        ///عتل بعد ذلک زنیم
        ///ان کان ذا مال وبنین
        ///اذا تتلى علیه ایاتنا قال اساطیر الاولین
        ///سنسمه على الخرطوم
        ///انا بلوناهم کما بلونا اصحاب الجن اذ اقسموا لیصرمنها مصبحین
        ///ولا یستثنون
        ///فطاف علیها طائف من ربک وهم نائمون
        ///فاصبحت کالصریم
        ///فتنادوا مصبحین [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _68 {
            get {
                return ResourceManager.GetString("_68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الحاق
        ///ما الحاق
        ///وما ادراک ما الحاق
        ///کذبت ثمود وعاد بالقارع
        ///فاما ثمود فاهلکوا بالطاغی
        ///واما عاد فاهلکوا بریح صرصر عاتی
        ///سخرها علیهم سبع لیال وثمانی ایام حسوما فترى القوم فیها صرعى کانهم اعجاز نخل خاوی
        ///فهل ترى لهم من باقی
        ///وجا فرعون ومن قبله والموتفکات بالخاطئ
        ///فعصوا رسول ربهم فاخذهم اخذ رابی
        ///انا لما طغى الما حملناکم فی الجاری
        ///لنجعلها لکم تذکر وتعیها اذن واعی
        ///فاذا نفخ فی الصور نفخ واحد
        ///وحملت الارض والجبال فدکتا دک واحد
        ///فیومئذ وقعت الواقع
        ///وانشقت السما فهی یومئذ واهی
        ///والملک على ارجائها ویحمل عر [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _69 {
            get {
                return ResourceManager.GetString("_69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم المص
        ///کتاب انزل الیک فلا یکن فی صدرک حرج منه لتنذر به وذکرى للمومنین
        ///اتبعوا ما انزل الیکم من ربکم ولا تتبعوا من دونه اولیا قلیلا ما تذکرون
        ///وکم من قری اهلکناها فجاها باسنا بیاتا او هم قائلون
        ///فما کان دعواهم اذ جاهم باسنا الا ان قالوا انا کنا ظالمین
        ///فلنسالن الذین ارسل الیهم ولنسالن المرسلین
        ///فلنقصن علیهم بعلم وما کنا غائبین
        ///والوزن یومئذ الحق فمن ثقلت موازینه فاولئک هم المفلحون
        ///ومن خفت موازینه فاولئک الذین خسروا انفسهم بما کانوا بایاتنا یظلمون
        ///ولقد مکناکم فی الارض وجعلنا لکم فیها معایش قلیل [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سال سائل بعذاب واقع
        ///للکافرین لیس له دافع
        ///من الله ذی المعارج
        ///تعرج الملائک والروح الیه فی یوم کان مقداره خمسین الف سن
        ///فاصبر صبرا جمیلا
        ///انهم یرونه بعیدا
        ///ونراه قریبا
        ///یوم تکون السما کالمهل
        ///وتکون الجبال کالعهن
        ///ولا یسال حمیم حمیما
        ///یبصرونهم یود المجرم لو یفتدی من عذاب یومئذ ببنیه
        ///وصاحبته واخیه
        ///وفصیلته التی توویه
        ///ومن فی الارض جمیعا ثم ینجیه
        ///کلا انها لظى
        ///نزاع للشوى
        ///تدعو من ادبر وتولى
        ///وجمع فاوعى
        ///ان الانسان خلق هلوعا
        ///اذا مسه الشر جزوعا
        ///واذا مسه الخیر منوعا
        ///الا المصلین
        ///الذین هم على صلاتهم دائمون
        ///و [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _70 {
            get {
                return ResourceManager.GetString("_70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم انا ارسلنا نوحا الى قومه ان انذر قومک من قبل ان یاتیهم عذاب الیم
        ///قال یا قوم انی لکم نذیر مبین
        ///ان اعبدوا الله واتقوه واطیعون
        ///یغفر لکم من ذنوبکم ویوخرکم الى اجل مسمى ان اجل الله اذا جا لا یوخر لو کنتم تعلمون
        ///قال رب انی دعوت قومی لیلا ونهارا
        ///فلم یزدهم دعائی الا فرارا
        ///وانی کلما دعوتهم لتغفر لهم جعلوا اصابعهم فی اذانهم واستغشوا ثیابهم واصروا واستکبروا استکبارا
        ///ثم انی دعوتهم جهارا
        ///ثم انی اعلنت لهم واسررت لهم اسرارا
        ///فقلت استغفروا ربکم انه کان غفارا
        ///یرسل السما علیکم مدرارا
        ///ویمددکم باموال وبنی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _71 {
            get {
                return ResourceManager.GetString("_71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم قل اوحی الی انه استمع نفر من الجن فقالوا انا سمعنا قرانا عجبا
        ///یهدی الى الرشد فامنا به ولن نشرک بربنا احدا
        ///وانه تعالى جد ربنا ما اتخذ صاحب ولا ولدا
        ///وانه کان یقول سفیهنا على الله شططا
        ///وانا ظننا ان لن تقول الانس والجن على الله کذبا
        ///وانه کان رجال من الانس یعوذون برجال من الجن فزادوهم رهقا
        ///وانهم ظنوا کما ظننتم ان لن یبعث الله احدا
        ///وانا لمسنا السما فوجدناها ملئت حرسا شدیدا وشهبا
        ///وانا کنا نقعد منها مقاعد للسمع فمن یستمع الان یجد له شهابا رصدا
        ///وانا لا ندری اشر ارید بمن فی الارض ام اراد بهم رب [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _72 {
            get {
                return ResourceManager.GetString("_72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها المزمل
        ///قم اللیل الا قلیلا
        ///نصفه او انقص منه قلیلا
        ///او زد علیه ورتل القران ترتیلا
        ///انا سنلقی علیک قولا ثقیلا
        ///ان ناشئ اللیل هی اشد وطئا واقوم قیلا
        ///ان لک فی النهار سبحا طویلا
        ///واذکر اسم ربک وتبتل الیه تبتیلا
        ///رب المشرق والمغرب لا اله الا هو فاتخذه وکیلا
        ///واصبر على ما یقولون واهجرهم هجرا جمیلا
        ///وذرنی والمکذبین اولی النعم ومهلهم قلیلا
        ///ان لدینا انکالا وجحیما
        ///وطعاما ذا غص وعذابا الیما
        ///یوم ترجف الارض والجبال وکانت الجبال کثیبا مهیلا
        ///انا ارسلنا الیکم رسولا شاهدا علیکم کما ارسلنا الى فرعون رسو [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _73 {
            get {
                return ResourceManager.GetString("_73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یا ایها المدثر
        ///قم فانذر
        ///وربک فکبر
        ///وثیابک فطهر
        ///والرجز فاهجر
        ///ولا تمنن تستکثر
        ///ولربک فاصبر
        ///فاذا نقر فی الناقور
        ///فذلک یومئذ یوم عسیر
        ///على الکافرین غیر یسیر
        ///ذرنی ومن خلقت وحیدا
        ///وجعلت له مالا ممدودا
        ///وبنین شهودا
        ///ومهدت له تمهیدا
        ///ثم یطمع ان ازید
        ///کلا انه کان لایاتنا عنیدا
        ///سارهقه صعودا
        ///انه فکر وقدر
        ///فقتل کیف قدر
        ///ثم قتل کیف قدر
        ///ثم نظر
        ///ثم عبس وبسر
        ///ثم ادبر واستکبر
        ///فقال ان هذا الا سحر یوثر
        ///ان هذا الا قول البشر
        ///ساصلیه سقر
        ///وما ادراک ما سقر
        ///لا تبقی ولا تذر
        ///لواح للبشر
        ///علیها تسع عشر
        ///وما جعلنا اصحاب النار الا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _74 {
            get {
                return ResourceManager.GetString("_74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم لا اقسم بیوم القیام
        ///ولا اقسم بالنفس اللوام
        ///ایحسب الانسان الن نجمع عظامه
        ///بلى قادرین على ان نسوی بنانه
        ///بل یرید الانسان لیفجر امامه
        ///یسال ایان یوم القیام
        ///فاذا برق البصر
        ///وخسف القمر
        ///وجمع الشمس والقمر
        ///یقول الانسان یومئذ این المفر
        ///کلا لا وزر
        ///الى ربک یومئذ المستقر
        ///ینبا الانسان یومئذ بما قدم واخر
        ///بل الانسان على نفسه بصیر
        ///ولو القى معاذیره
        ///لا تحرک به لسانک لتعجل به
        ///ان علینا جمعه وقرانه
        ///فاذا قراناه فاتبع قرانه
        ///ثم ان علینا بیانه
        ///کلا بل تحبون العاجل
        ///وتذرون الاخر
        ///وجوه یومئذ ناضر
        ///الى ربها ناظر
        ///ووجوه ی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _75 {
            get {
                return ResourceManager.GetString("_75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم هل اتى على الانسان حین من الدهر لم یکن شیئا مذکورا
        ///انا خلقنا الانسان من نطف امشاج نبتلیه فجعلناه سمیعا بصیرا
        ///انا هدیناه السبیل اما شاکرا واما کفورا
        ///انا اعتدنا للکافرین سلاسل واغلالا وسعیرا
        ///ان الابرار یشربون من کاس کان مزاجها کافورا
        ///عینا یشرب بها عباد الله یفجرونها تفجیرا
        ///یوفون بالنذر ویخافون یوما کان شره مستطیرا
        ///ویطعمون الطعام على حبه مسکینا ویتیما واسیرا
        ///انما نطعمکم لوجه الله لا نرید منکم جزا ولا شکورا
        ///انا نخاف من ربنا یوما عبوسا قمطریرا
        ///فوقاهم الله شر ذلک الیوم ولقاهم نضر وسرورا
        ///وجز [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _76 {
            get {
                return ResourceManager.GetString("_76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والمرسلات عرفا
        ///فالعاصفات عصفا
        ///والناشرات نشرا
        ///فالفارقات فرقا
        ///فالملقیات ذکرا
        ///عذرا او نذرا
        ///انما توعدون لواقع
        ///فاذا النجوم طمست
        ///واذا السما فرجت
        ///واذا الجبال نسفت
        ///واذا الرسل اقتت
        ///لای یوم اجلت
        ///لیوم الفصل
        ///وما ادراک ما یوم الفصل
        ///ویل یومئذ للمکذبین
        ///الم نهلک الاولین
        ///ثم نتبعهم الاخرین
        ///کذلک نفعل بالمجرمین
        ///ویل یومئذ للمکذبین
        ///الم نخلقکم من ما مهین
        ///فجعلناه فی قرار مکین
        ///الى قدر معلوم
        ///فقدرنا فنعم القادرون
        ///ویل یومئذ للمکذبین
        ///الم نجعل الارض کفاتا
        ///احیا وامواتا
        ///وجعلنا فیها رواسی شامخات واسقیناکم ما فراتا
        ///وی [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _77 {
            get {
                return ResourceManager.GetString("_77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم عم یتسالون
        ///عن النبا العظیم
        ///الذی هم فیه مختلفون
        ///کلا سیعلمون
        ///ثم کلا سیعلمون
        ///الم نجعل الارض مهادا
        ///والجبال اوتادا
        ///وخلقناکم ازواجا
        ///وجعلنا نومکم سباتا
        ///وجعلنا اللیل لباسا
        ///وجعلنا النهار معاشا
        ///وبنینا فوقکم سبعا شدادا
        ///وجعلنا سراجا وهاجا
        ///وانزلنا من المعصرات ما ثجاجا
        ///لنخرج به حبا ونباتا
        ///وجنات الفافا
        ///ان یوم الفصل کان میقاتا
        ///یوم ینفخ فی الصور فتاتون افواجا
        ///وفتحت السما فکانت ابوابا
        ///وسیرت الجبال فکانت سرابا
        ///ان جهنم کانت مرصادا
        ///للطاغین مابا
        ///لابثین فیها احقابا
        ///لا یذوقون فیها بردا ولا شرابا
        ///الا حمیما وغ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _78 {
            get {
                return ResourceManager.GetString("_78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والنازعات غرقا
        ///والناشطات نشطا
        ///والسابحات سبحا
        ///فالسابقات سبقا
        ///فالمدبرات امرا
        ///یوم ترجف الراجف
        ///تتبعها الرادف
        ///قلوب یومئذ واجف
        ///ابصارها خاشع
        ///یقولون اانا لمردودون فی الحافر
        ///ااذا کنا عظاما نخر
        ///قالوا تلک اذا کر خاسر
        ///فانما هی زجر واحد
        ///فاذا هم بالساهر
        ///هل اتاک حدیث موسى
        ///اذ ناداه ربه بالواد المقدس طوى
        ///اذهب الى فرعون انه طغى
        ///فقل هل لک الى ان تزکى
        ///واهدیک الى ربک فتخشى
        ///فاراه الای الکبرى
        ///فکذب وعصى
        ///ثم ادبر یسعى
        ///فحشر فنادى
        ///فقال انا ربکم الاعلى
        ///فاخذه الله نکال الاخر والاولى
        ///ان فی ذلک لعبر لمن یخشى
        ///اانتم ا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _79 {
            get {
                return ResourceManager.GetString("_79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم یسالونک عن الانفال قل الانفال لله والرسول فاتقوا الله واصلحوا ذات بینکم واطیعوا الله ورسوله ان کنتم مومنین
        ///انما المومنون الذین اذا ذکر الله وجلت قلوبهم واذا تلیت علیهم ایاته زادتهم ایمانا وعلى ربهم یتوکلون
        ///الذین یقیمون الصلا ومما رزقناهم ینفقون
        ///اولئک هم المومنون حقا لهم درجات عند ربهم ومغفر ورزق کریم
        ///کما اخرجک ربک من بیتک بالحق وان فریقا من المومنین لکارهون
        ///یجادلونک فی الحق بعد ما تبین کانما یساقون الى الموت وهم ینظرون
        ///واذ یعدکم الله احدى الطائفتین انها لکم وتودون ان غیر ذات الشوک تکو [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم عبس وتولى
        ///ان جاه الاعمى
        ///وما یدریک لعله یزکى
        ///او یذکر فتنفعه الذکرى
        ///اما من استغنى
        ///فانت له تصدى
        ///وما علیک الا یزکى
        ///واما من جاک یسعى
        ///وهو یخشى
        ///فانت عنه تلهى
        ///کلا انها تذکر
        ///فمن شا ذکره
        ///فی صحف مکرم
        ///مرفوع مطهر
        ///بایدی سفر
        ///کرام برر
        ///قتل الانسان ما اکفره
        ///من ای شی خلقه
        ///من نطف خلقه فقدره
        ///ثم السبیل یسره
        ///ثم اماته فاقبره
        ///ثم اذا شا انشره
        ///کلا لما یقض ما امره
        ///فلینظر الانسان الى طعامه
        ///انا صببنا الما صبا
        ///ثم شققنا الارض شقا
        ///فانبتنا فیها حبا
        ///وعنبا وقضبا
        ///وزیتونا ونخلا
        ///وحدائق غلبا
        ///وفاکه وابا
        ///متاعا لکم ولانعامکم
        ///ف [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("_80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا الشمس کورت
        ///واذا النجوم انکدرت
        ///واذا الجبال سیرت
        ///واذا العشار عطلت
        ///واذا الوحوش حشرت
        ///واذا البحار سجرت
        ///واذا النفوس زوجت
        ///واذا الموود سئلت
        ///بای ذنب قتلت
        ///واذا الصحف نشرت
        ///واذا السما کشطت
        ///واذا الجحیم سعرت
        ///واذا الجن ازلفت
        ///علمت نفس ما احضرت
        ///فلا اقسم بالخنس
        ///الجوار الکنس
        ///واللیل اذا عسعس
        ///والصبح اذا تنفس
        ///انه لقول رسول کریم
        ///ذی قو عند ذی العرش مکین
        ///مطاع ثم امین
        ///وما صاحبکم بمجنون
        ///ولقد راه بالافق المبین
        ///وما هو على الغیب بضنین
        ///وما هو بقول شیطان رجیم
        ///فاین تذهبون
        ///ان هو الا ذکر للعالمین
        ///لمن شا منکم ان یست [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _81 {
            get {
                return ResourceManager.GetString("_81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا السما انفطرت
        ///واذا الکواکب انتثرت
        ///واذا البحار فجرت
        ///واذا القبور بعثرت
        ///علمت نفس ما قدمت واخرت
        ///یا ایها الانسان ما غرک بربک الکریم
        ///الذی خلقک فسواک فعدلک
        ///فی ای صور ما شا رکبک
        ///کلا بل تکذبون بالدین
        ///وان علیکم لحافظین
        ///کراما کاتبین
        ///یعلمون ما تفعلون
        ///ان الابرار لفی نعیم
        ///وان الفجار لفی جحیم
        ///یصلونها یوم الدین
        ///وما هم عنها بغائبین
        ///وما ادراک ما یوم الدین
        ///ثم ما ادراک ما یوم الدین
        ///یوم لا تملک نفس لنفس شیئا والامر یومئذ لله.
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("_82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم ویل للمطففین
        ///الذین اذا اکتالوا على الناس یستوفون
        ///واذا کالوهم او وزنوهم یخسرون
        ///الا یظن اولئک انهم مبعوثون
        ///لیوم عظیم
        ///یوم یقوم الناس لرب العالمین
        ///کلا ان کتاب الفجار لفی سجین
        ///وما ادراک ما سجین
        ///کتاب مرقوم
        ///ویل یومئذ للمکذبین
        ///الذین یکذبون بیوم الدین
        ///وما یکذب به الا کل معتد اثیم
        ///اذا تتلى علیه ایاتنا قال اساطیر الاولین
        ///کلا بل ران على قلوبهم ما کانوا یکسبون
        ///کلا انهم عن ربهم یومئذ لمحجوبون
        ///ثم انهم لصالو الجحیم
        ///ثم یقال هذا الذی کنتم به تکذبون
        ///کلا ان کتاب الابرار لفی علیین
        ///وما ادراک ما علیون
        ///کتاب  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _83 {
            get {
                return ResourceManager.GetString("_83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا السما انشقت
        ///واذنت لربها وحقت
        ///واذا الارض مدت
        ///والقت ما فیها وتخلت
        ///واذنت لربها وحقت
        ///یا ایها الانسان انک کادح الى ربک کدحا فملاقیه
        ///فاما من اوتی کتابه بیمینه
        ///فسوف یحاسب حسابا یسیرا
        ///وینقلب الى اهله مسرورا
        ///واما من اوتی کتابه ورا ظهره
        ///فسوف یدعو ثبورا
        ///ویصلى سعیرا
        ///انه کان فی اهله مسرورا
        ///انه ظن ان لن یحور
        ///بلى ان ربه کان به بصیرا
        ///فلا اقسم بالشفق
        ///واللیل وما وسق
        ///والقمر اذا اتسق
        ///لترکبن طبقا عن طبق
        ///فما لهم لا یومنون
        ///واذا قرئ علیهم القران لا یسجدون
        ///بل الذین کفروا یکذبون
        ///والله اعلم بما یوعون
        ///فبشرهم [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _84 {
            get {
                return ResourceManager.GetString("_84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والسما ذات البروج
        ///والیوم الموعود
        ///وشاهد ومشهود
        ///قتل اصحاب الاخدود
        ///النار ذات الوقود
        ///اذ هم علیها قعود
        ///وهم على ما یفعلون بالمومنین شهود
        ///وما نقموا منهم الا ان یومنوا بالله العزیز الحمید
        ///الذی له ملک السماوات والارض والله على کل شی شهید
        ///ان الذین فتنوا المومنین والمومنات ثم لم یتوبوا فلهم عذاب جهنم ولهم عذاب الحریق
        ///ان الذین امنوا وعملوا الصالحات لهم جنات تجری من تحتها الانهار ذلک الفوز الکبیر
        ///ان بطش ربک لشدید
        ///انه هو یبدئ ویعید
        ///وهو الغفور الودود
        ///ذو العرش المجید
        ///فعال لما یرید
        ///هل اتاک حدیث الجنود [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _85 {
            get {
                return ResourceManager.GetString("_85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والسما والطارق
        ///وما ادراک ما الطارق
        ///النجم الثاقب
        ///ان کل نفس لما علیها حافظ
        ///فلینظر الانسان مم خلق
        ///خلق من ما دافق
        ///یخرج من بین الصلب والترائب
        ///انه على رجعه لقادر
        ///یوم تبلى السرائر
        ///فما له من قو ولا ناصر
        ///والسما ذات الرجع
        ///والارض ذات الصدع
        ///انه لقول فصل
        ///وما هو بالهزل
        ///انهم یکیدون کیدا
        ///واکید کیدا
        ///فمهل الکافرین امهلهم رویدا.
        /// </summary>
        internal static string _86 {
            get {
                return ResourceManager.GetString("_86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم سبح اسم ربک الاعلى
        ///الذی خلق فسوى
        ///والذی قدر فهدى
        ///والذی اخرج المرعى
        ///فجعله غثا احوى
        ///سنقرئک فلا تنسى
        ///الا ما شا الله انه یعلم الجهر وما یخفى
        ///ونیسرک للیسرى
        ///فذکر ان نفعت الذکرى
        ///سیذکر من یخشى
        ///ویتجنبها الاشقى
        ///الذی یصلى النار الکبرى
        ///ثم لا یموت فیها ولا یحیى
        ///قد افلح من تزکى
        ///وذکر اسم ربه فصلى
        ///بل توثرون الحیا الدنیا
        ///والاخر خیر وابقى
        ///ان هذا لفی الصحف الاولى
        ///صحف ابراهیم وموسى.
        /// </summary>
        internal static string _87 {
            get {
                return ResourceManager.GetString("_87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم هل اتاک حدیث الغاشی
        ///وجوه یومئذ خاشع
        ///عامل ناصب
        ///تصلى نارا حامی
        ///تسقى من عین انی
        ///لیس لهم طعام الا من ضریع
        ///لا یسمن ولا یغنی من جوع
        ///وجوه یومئذ ناعم
        ///لسعیها راضی
        ///فی جن عالی
        ///لا تسمع فیها لاغی
        ///فیها عین جاری
        ///فیها سرر مرفوع
        ///واکواب موضوع
        ///ونمارق مصفوف
        ///وزرابی مبثوث
        ///افلا ینظرون الى الابل کیف خلقت
        ///والى السما کیف رفعت
        ///والى الجبال کیف نصبت
        ///والى الارض کیف سطحت
        ///فذکر انما انت مذکر
        ///لست علیهم بمصیطر
        ///الا من تولى وکفر
        ///فیعذبه الله العذاب الاکبر
        ///ان الینا ایابهم
        ///ثم ان علینا حسابهم.
        /// </summary>
        internal static string _88 {
            get {
                return ResourceManager.GetString("_88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والفجر
        ///ولیال عشر
        ///والشفع والوتر
        ///واللیل اذا یسر
        ///هل فی ذلک قسم لذی حجر
        ///الم تر کیف فعل ربک بعاد
        ///ارم ذات العماد
        ///التی لم یخلق مثلها فی البلاد
        ///وثمود الذین جابوا الصخر بالواد
        ///وفرعون ذی الاوتاد
        ///الذین طغوا فی البلاد
        ///فاکثروا فیها الفساد
        ///فصب علیهم ربک سوط عذاب
        ///ان ربک لبالمرصاد
        ///فاما الانسان اذا ما ابتلاه ربه فاکرمه ونعمه فیقول ربی اکرمن
        ///واما اذا ما ابتلاه فقدر علیه رزقه فیقول ربی اهانن
        ///کلا بل لا تکرمون الیتیم
        ///ولا تحاضون على طعام المسکین
        ///وتاکلون التراث اکلا لما
        ///وتحبون المال حبا جما
        ///کلا اذا دکت الار [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _89 {
            get {
                return ResourceManager.GetString("_89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برا من الله ورسوله الى الذین عاهدتم من المشرکین
        ///فسیحوا فی الارض اربع اشهر واعلموا انکم غیر معجزی الله وان الله مخزی الکافرین
        ///واذان من الله ورسوله الى الناس یوم الحج الاکبر ان الله بری من المشرکین ورسوله فان تبتم فهو خیر لکم وان تولیتم فاعلموا انکم غیر معجزی الله وبشر الذین کفروا بعذاب الیم
        ///الا الذین عاهدتم من المشرکین ثم لم ینقصوکم شیئا ولم یظاهروا علیکم احدا فاتموا الیهم عهدهم الى مدتهم ان الله یحب المتقین
        ///فاذا انسلخ الاشهر الحرم فاقتلوا المشرکین حیث وجدتموهم وخذوهم واحصروهم واقعدوا لهم کل مرصد فان تابوا و [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم لا اقسم بهذا البلد
        ///وانت حل بهذا البلد
        ///ووالد وما ولد
        ///لقد خلقنا الانسان فی کبد
        ///ایحسب ان لن یقدر علیه احد
        ///یقول اهلکت مالا لبدا
        ///ایحسب ان لم یره احد
        ///الم نجعل له عینین
        ///ولسانا وشفتین
        ///وهدیناه النجدین
        ///فلا اقتحم العقب
        ///وما ادراک ما العقب
        ///فک رقب
        ///او اطعام فی یوم ذی مسغب
        ///یتیما ذا مقرب
        ///او مسکینا ذا مترب
        ///ثم کان من الذین امنوا وتواصوا بالصبر وتواصوا بالمرحم
        ///اولئک اصحاب المیمن
        ///والذین کفروا بایاتنا هم اصحاب المشام
        ///علیهم نار موصد.
        /// </summary>
        internal static string _90 {
            get {
                return ResourceManager.GetString("_90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والشمس وضحاها
        ///والقمر اذا تلاها
        ///والنهار اذا جلاها
        ///واللیل اذا یغشاها
        ///والسما وما بناها
        ///والارض وما طحاها
        ///ونفس وما سواها
        ///فالهمها فجورها وتقواها
        ///قد افلح من زکاها
        ///وقد خاب من دساها
        ///کذبت ثمود بطغواها
        ///اذ انبعث اشقاها
        ///فقال لهم رسول الله ناق الله وسقیاها
        ///فکذبوه فعقروها فدمدم علیهم ربهم بذنبهم فسواها
        ///ولا یخاف عقباها.
        /// </summary>
        internal static string _91 {
            get {
                return ResourceManager.GetString("_91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم واللیل اذا یغشى
        ///والنهار اذا تجلى
        ///وما خلق الذکر والانثى
        ///ان سعیکم لشتى
        ///فاما من اعطى واتقى
        ///وصدق بالحسنى
        ///فسنیسره للیسرى
        ///واما من بخل واستغنى
        ///وکذب بالحسنى
        ///فسنیسره للعسرى
        ///وما یغنی عنه ماله اذا تردى
        ///ان علینا للهدى
        ///وان لنا للاخر والاولى
        ///فانذرتکم نارا تلظى
        ///لا یصلاها الا الاشقى
        ///الذی کذب وتولى
        ///وسیجنبها الاتقى
        ///الذی یوتی ماله یتزکى
        ///وما لاحد عنده من نعم تجزى
        ///الا ابتغا وجه ربه الاعلى
        ///ولسوف یرضى.
        /// </summary>
        internal static string _92 {
            get {
                return ResourceManager.GetString("_92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والضحى
        ///واللیل اذا سجى
        ///ما ودعک ربک وما قلى
        ///وللاخر خیر لک من الاولى
        ///ولسوف یعطیک ربک فترضى
        ///الم یجدک یتیما فاوى
        ///ووجدک ضالا فهدى
        ///ووجدک عائلا فاغنى
        ///فاما الیتیم فلا تقهر
        ///واما السائل فلا تنهر
        ///واما بنعم ربک فحدث.
        /// </summary>
        internal static string _93 {
            get {
                return ResourceManager.GetString("_93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم الم نشرح لک صدرک
        ///ووضعنا عنک وزرک
        ///الذی انقض ظهرک
        ///ورفعنا لک ذکرک
        ///فان مع العسر یسرا
        ///ان مع العسر یسرا
        ///فاذا فرغت فانصب
        ///والى ربک فارغب.
        /// </summary>
        internal static string _94 {
            get {
                return ResourceManager.GetString("_94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم والتین والزیتون
        ///وطور سینین
        ///وهذا البلد الامین
        ///لقد خلقنا الانسان فی احسن تقویم
        ///ثم رددناه اسفل سافلین
        ///الا الذین امنوا وعملوا الصالحات فلهم اجر غیر ممنون
        ///فما یکذبک بعد بالدین
        ///الیس الله باحکم الحاکمین.
        /// </summary>
        internal static string _95 {
            get {
                return ResourceManager.GetString("_95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اقرا باسم ربک الذی خلق
        ///خلق الانسان من علق
        ///اقرا وربک الاکرم
        ///الذی علم بالقلم
        ///علم الانسان ما لم یعلم
        ///کلا ان الانسان لیطغى
        ///ان راه استغنى
        ///ان الى ربک الرجعى
        ///ارایت الذی ینهى
        ///عبدا اذا صلى
        ///ارایت ان کان على الهدى
        ///او امر بالتقوى
        ///ارایت ان کذب وتولى
        ///الم یعلم بان الله یرى
        ///کلا لئن لم ینته لنسفعا بالناصی
        ///ناصی کاذب خاطئ
        ///فلیدع نادیه
        ///سندع الزبانی
        ///کلا لا تطعه واسجد واقترب.
        /// </summary>
        internal static string _96 {
            get {
                return ResourceManager.GetString("_96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم انا انزلناه فی لیل القدر
        ///وما ادراک ما لیل القدر
        ///لیل القدر خیر من الف شهر
        ///تنزل الملائک والروح فیها باذن ربهم من کل امر
        ///سلام هی حتى مطلع الفجر.
        /// </summary>
        internal static string _97 {
            get {
                return ResourceManager.GetString("_97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم لم یکن الذین کفروا من اهل الکتاب والمشرکین منفکین حتى تاتیهم البین
        ///رسول من الله یتلو صحفا مطهر
        ///فیها کتب قیم
        ///وما تفرق الذین اوتوا الکتاب الا من بعد ما جاتهم البین
        ///وما امروا الا لیعبدوا الله مخلصین له الدین حنفا ویقیموا الصلا ویوتوا الزکا وذلک دین القیم
        ///ان الذین کفروا من اهل الکتاب والمشرکین فی نار جهنم خالدین فیها اولئک هم شر البری
        ///ان الذین امنوا وعملوا الصالحات اولئک هم خیر البری
        ///جزاوهم عند ربهم جنات عدن تجری من تحتها الانهار خالدین فیها ابدا رضی الله عنهم ورضوا عنه ذلک لمن خشی ربه.
        /// </summary>
        internal static string _98 {
            get {
                return ResourceManager.GetString("_98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بسم الله الرحمن الرحیم اذا زلزلت الارض زلزالها
        ///واخرجت الارض اثقالها
        ///وقال الانسان ما لها
        ///یومئذ تحدث اخبارها
        ///بان ربک اوحى لها
        ///یومئذ یصدر الناس اشتاتا لیروا اعمالهم
        ///فمن یعمل مثقال ذر خیرا یره
        ///ومن یعمل مثقال ذر شرا یره.
        /// </summary>
        internal static string _99 {
            get {
                return ResourceManager.GetString("_99", resourceCulture);
            }
        }
    }
}
